// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: goadesign_goagen_liquent_portfolio_rpc.proto

package liquent_portfolio_rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LiquentPortfolioRPCClient is the client API for LiquentPortfolioRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiquentPortfolioRPCClient interface {
	// Provide a list of addresses holding a specific token
	TokenHolders(ctx context.Context, in *TokenHoldersRequest, opts ...grpc.CallOption) (*TokenHoldersResponse, error)
	// Provide the account's portfolio
	AccountPortfolio(ctx context.Context, in *AccountPortfolioRequest, opts ...grpc.CallOption) (*AccountPortfolioResponse, error)
	// Provide the account's portfolio balances
	AccountPortfolioBalances(ctx context.Context, in *AccountPortfolioBalancesRequest, opts ...grpc.CallOption) (*AccountPortfolioBalancesResponse, error)
	// Stream the account's portfolio
	StreamAccountPortfolio(ctx context.Context, in *StreamAccountPortfolioRequest, opts ...grpc.CallOption) (LiquentPortfolioRPC_StreamAccountPortfolioClient, error)
}

type liquentPortfolioRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewLiquentPortfolioRPCClient(cc grpc.ClientConnInterface) LiquentPortfolioRPCClient {
	return &liquentPortfolioRPCClient{cc}
}

func (c *liquentPortfolioRPCClient) TokenHolders(ctx context.Context, in *TokenHoldersRequest, opts ...grpc.CallOption) (*TokenHoldersResponse, error) {
	out := new(TokenHoldersResponse)
	err := c.cc.Invoke(ctx, "/liquent_portfolio_rpc.LiquentPortfolioRPC/TokenHolders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentPortfolioRPCClient) AccountPortfolio(ctx context.Context, in *AccountPortfolioRequest, opts ...grpc.CallOption) (*AccountPortfolioResponse, error) {
	out := new(AccountPortfolioResponse)
	err := c.cc.Invoke(ctx, "/liquent_portfolio_rpc.LiquentPortfolioRPC/AccountPortfolio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentPortfolioRPCClient) AccountPortfolioBalances(ctx context.Context, in *AccountPortfolioBalancesRequest, opts ...grpc.CallOption) (*AccountPortfolioBalancesResponse, error) {
	out := new(AccountPortfolioBalancesResponse)
	err := c.cc.Invoke(ctx, "/liquent_portfolio_rpc.LiquentPortfolioRPC/AccountPortfolioBalances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentPortfolioRPCClient) StreamAccountPortfolio(ctx context.Context, in *StreamAccountPortfolioRequest, opts ...grpc.CallOption) (LiquentPortfolioRPC_StreamAccountPortfolioClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentPortfolioRPC_ServiceDesc.Streams[0], "/liquent_portfolio_rpc.LiquentPortfolioRPC/StreamAccountPortfolio", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentPortfolioRPCStreamAccountPortfolioClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentPortfolioRPC_StreamAccountPortfolioClient interface {
	Recv() (*StreamAccountPortfolioResponse, error)
	grpc.ClientStream
}

type liquentPortfolioRPCStreamAccountPortfolioClient struct {
	grpc.ClientStream
}

func (x *liquentPortfolioRPCStreamAccountPortfolioClient) Recv() (*StreamAccountPortfolioResponse, error) {
	m := new(StreamAccountPortfolioResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LiquentPortfolioRPCServer is the server API for LiquentPortfolioRPC service.
// All implementations must embed UnimplementedLiquentPortfolioRPCServer
// for forward compatibility
type LiquentPortfolioRPCServer interface {
	// Provide a list of addresses holding a specific token
	TokenHolders(context.Context, *TokenHoldersRequest) (*TokenHoldersResponse, error)
	// Provide the account's portfolio
	AccountPortfolio(context.Context, *AccountPortfolioRequest) (*AccountPortfolioResponse, error)
	// Provide the account's portfolio balances
	AccountPortfolioBalances(context.Context, *AccountPortfolioBalancesRequest) (*AccountPortfolioBalancesResponse, error)
	// Stream the account's portfolio
	StreamAccountPortfolio(*StreamAccountPortfolioRequest, LiquentPortfolioRPC_StreamAccountPortfolioServer) error
	mustEmbedUnimplementedLiquentPortfolioRPCServer()
}

// UnimplementedLiquentPortfolioRPCServer must be embedded to have forward compatible implementations.
type UnimplementedLiquentPortfolioRPCServer struct {
}

func (UnimplementedLiquentPortfolioRPCServer) TokenHolders(context.Context, *TokenHoldersRequest) (*TokenHoldersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenHolders not implemented")
}
func (UnimplementedLiquentPortfolioRPCServer) AccountPortfolio(context.Context, *AccountPortfolioRequest) (*AccountPortfolioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountPortfolio not implemented")
}
func (UnimplementedLiquentPortfolioRPCServer) AccountPortfolioBalances(context.Context, *AccountPortfolioBalancesRequest) (*AccountPortfolioBalancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountPortfolioBalances not implemented")
}
func (UnimplementedLiquentPortfolioRPCServer) StreamAccountPortfolio(*StreamAccountPortfolioRequest, LiquentPortfolioRPC_StreamAccountPortfolioServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAccountPortfolio not implemented")
}
func (UnimplementedLiquentPortfolioRPCServer) mustEmbedUnimplementedLiquentPortfolioRPCServer() {}

// UnsafeLiquentPortfolioRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiquentPortfolioRPCServer will
// result in compilation errors.
type UnsafeLiquentPortfolioRPCServer interface {
	mustEmbedUnimplementedLiquentPortfolioRPCServer()
}

func RegisterLiquentPortfolioRPCServer(s grpc.ServiceRegistrar, srv LiquentPortfolioRPCServer) {
	s.RegisterService(&LiquentPortfolioRPC_ServiceDesc, srv)
}

func _LiquentPortfolioRPC_TokenHolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenHoldersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentPortfolioRPCServer).TokenHolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_portfolio_rpc.LiquentPortfolioRPC/TokenHolders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentPortfolioRPCServer).TokenHolders(ctx, req.(*TokenHoldersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentPortfolioRPC_AccountPortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountPortfolioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentPortfolioRPCServer).AccountPortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_portfolio_rpc.LiquentPortfolioRPC/AccountPortfolio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentPortfolioRPCServer).AccountPortfolio(ctx, req.(*AccountPortfolioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentPortfolioRPC_AccountPortfolioBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountPortfolioBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentPortfolioRPCServer).AccountPortfolioBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_portfolio_rpc.LiquentPortfolioRPC/AccountPortfolioBalances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentPortfolioRPCServer).AccountPortfolioBalances(ctx, req.(*AccountPortfolioBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentPortfolioRPC_StreamAccountPortfolio_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAccountPortfolioRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentPortfolioRPCServer).StreamAccountPortfolio(m, &liquentPortfolioRPCStreamAccountPortfolioServer{stream})
}

type LiquentPortfolioRPC_StreamAccountPortfolioServer interface {
	Send(*StreamAccountPortfolioResponse) error
	grpc.ServerStream
}

type liquentPortfolioRPCStreamAccountPortfolioServer struct {
	grpc.ServerStream
}

func (x *liquentPortfolioRPCStreamAccountPortfolioServer) Send(m *StreamAccountPortfolioResponse) error {
	return x.ServerStream.SendMsg(m)
}

// LiquentPortfolioRPC_ServiceDesc is the grpc.ServiceDesc for LiquentPortfolioRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiquentPortfolioRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "liquent_portfolio_rpc.LiquentPortfolioRPC",
	HandlerType: (*LiquentPortfolioRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TokenHolders",
			Handler:    _LiquentPortfolioRPC_TokenHolders_Handler,
		},
		{
			MethodName: "AccountPortfolio",
			Handler:    _LiquentPortfolioRPC_AccountPortfolio_Handler,
		},
		{
			MethodName: "AccountPortfolioBalances",
			Handler:    _LiquentPortfolioRPC_AccountPortfolioBalances_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAccountPortfolio",
			Handler:       _LiquentPortfolioRPC_StreamAccountPortfolio_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "goadesign_goagen_liquent_portfolio_rpc.proto",
}
