// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: goadesign_goagen_liquent_exchange_rpc.proto

package liquent_exchange_rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LiquentExchangeRPCClient is the client API for LiquentExchangeRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiquentExchangeRPCClient interface {
	// GetTx gets transaction details by hash.
	GetTx(ctx context.Context, in *GetTxRequest, opts ...grpc.CallOption) (*GetTxResponse, error)
	// PrepareTx generates a Web3-signable body for a Cosmos transaction
	PrepareTx(ctx context.Context, in *PrepareTxRequest, opts ...grpc.CallOption) (*PrepareTxResponse, error)
	// prepareEip712 generates EIP712 for an Liquent Message
	PrepareEip712(ctx context.Context, in *PrepareEip712Request, opts ...grpc.CallOption) (*PrepareEip712Response, error)
	// BroadcastTx broadcasts a signed Web3 transaction
	BroadcastTx(ctx context.Context, in *BroadcastTxRequest, opts ...grpc.CallOption) (*BroadcastTxResponse, error)
	// PrepareCosmosTx generates a Web3-signable body for a Cosmos transaction
	PrepareCosmosTx(ctx context.Context, in *PrepareCosmosTxRequest, opts ...grpc.CallOption) (*PrepareCosmosTxResponse, error)
	// BroadcastCosmosTx broadcasts a signed Web3 transaction
	BroadcastCosmosTx(ctx context.Context, in *BroadcastCosmosTxRequest, opts ...grpc.CallOption) (*BroadcastCosmosTxResponse, error)
	// Return fee payer information's
	GetFeePayer(ctx context.Context, in *GetFeePayerRequest, opts ...grpc.CallOption) (*GetFeePayerResponse, error)
}

type liquentExchangeRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewLiquentExchangeRPCClient(cc grpc.ClientConnInterface) LiquentExchangeRPCClient {
	return &liquentExchangeRPCClient{cc}
}

func (c *liquentExchangeRPCClient) GetTx(ctx context.Context, in *GetTxRequest, opts ...grpc.CallOption) (*GetTxResponse, error) {
	out := new(GetTxResponse)
	err := c.cc.Invoke(ctx, "/liquent_exchange_rpc.LiquentExchangeRPC/GetTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExchangeRPCClient) PrepareTx(ctx context.Context, in *PrepareTxRequest, opts ...grpc.CallOption) (*PrepareTxResponse, error) {
	out := new(PrepareTxResponse)
	err := c.cc.Invoke(ctx, "/liquent_exchange_rpc.LiquentExchangeRPC/PrepareTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExchangeRPCClient) PrepareEip712(ctx context.Context, in *PrepareEip712Request, opts ...grpc.CallOption) (*PrepareEip712Response, error) {
	out := new(PrepareEip712Response)
	err := c.cc.Invoke(ctx, "/liquent_exchange_rpc.LiquentExchangeRPC/PrepareEip712", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExchangeRPCClient) BroadcastTx(ctx context.Context, in *BroadcastTxRequest, opts ...grpc.CallOption) (*BroadcastTxResponse, error) {
	out := new(BroadcastTxResponse)
	err := c.cc.Invoke(ctx, "/liquent_exchange_rpc.LiquentExchangeRPC/BroadcastTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExchangeRPCClient) PrepareCosmosTx(ctx context.Context, in *PrepareCosmosTxRequest, opts ...grpc.CallOption) (*PrepareCosmosTxResponse, error) {
	out := new(PrepareCosmosTxResponse)
	err := c.cc.Invoke(ctx, "/liquent_exchange_rpc.LiquentExchangeRPC/PrepareCosmosTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExchangeRPCClient) BroadcastCosmosTx(ctx context.Context, in *BroadcastCosmosTxRequest, opts ...grpc.CallOption) (*BroadcastCosmosTxResponse, error) {
	out := new(BroadcastCosmosTxResponse)
	err := c.cc.Invoke(ctx, "/liquent_exchange_rpc.LiquentExchangeRPC/BroadcastCosmosTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExchangeRPCClient) GetFeePayer(ctx context.Context, in *GetFeePayerRequest, opts ...grpc.CallOption) (*GetFeePayerResponse, error) {
	out := new(GetFeePayerResponse)
	err := c.cc.Invoke(ctx, "/liquent_exchange_rpc.LiquentExchangeRPC/GetFeePayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiquentExchangeRPCServer is the server API for LiquentExchangeRPC service.
// All implementations must embed UnimplementedLiquentExchangeRPCServer
// for forward compatibility
type LiquentExchangeRPCServer interface {
	// GetTx gets transaction details by hash.
	GetTx(context.Context, *GetTxRequest) (*GetTxResponse, error)
	// PrepareTx generates a Web3-signable body for a Cosmos transaction
	PrepareTx(context.Context, *PrepareTxRequest) (*PrepareTxResponse, error)
	// prepareEip712 generates EIP712 for an Liquent Message
	PrepareEip712(context.Context, *PrepareEip712Request) (*PrepareEip712Response, error)
	// BroadcastTx broadcasts a signed Web3 transaction
	BroadcastTx(context.Context, *BroadcastTxRequest) (*BroadcastTxResponse, error)
	// PrepareCosmosTx generates a Web3-signable body for a Cosmos transaction
	PrepareCosmosTx(context.Context, *PrepareCosmosTxRequest) (*PrepareCosmosTxResponse, error)
	// BroadcastCosmosTx broadcasts a signed Web3 transaction
	BroadcastCosmosTx(context.Context, *BroadcastCosmosTxRequest) (*BroadcastCosmosTxResponse, error)
	// Return fee payer information's
	GetFeePayer(context.Context, *GetFeePayerRequest) (*GetFeePayerResponse, error)
	mustEmbedUnimplementedLiquentExchangeRPCServer()
}

// UnimplementedLiquentExchangeRPCServer must be embedded to have forward compatible implementations.
type UnimplementedLiquentExchangeRPCServer struct {
}

func (UnimplementedLiquentExchangeRPCServer) GetTx(context.Context, *GetTxRequest) (*GetTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTx not implemented")
}
func (UnimplementedLiquentExchangeRPCServer) PrepareTx(context.Context, *PrepareTxRequest) (*PrepareTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareTx not implemented")
}
func (UnimplementedLiquentExchangeRPCServer) PrepareEip712(context.Context, *PrepareEip712Request) (*PrepareEip712Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareEip712 not implemented")
}
func (UnimplementedLiquentExchangeRPCServer) BroadcastTx(context.Context, *BroadcastTxRequest) (*BroadcastTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastTx not implemented")
}
func (UnimplementedLiquentExchangeRPCServer) PrepareCosmosTx(context.Context, *PrepareCosmosTxRequest) (*PrepareCosmosTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareCosmosTx not implemented")
}
func (UnimplementedLiquentExchangeRPCServer) BroadcastCosmosTx(context.Context, *BroadcastCosmosTxRequest) (*BroadcastCosmosTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastCosmosTx not implemented")
}
func (UnimplementedLiquentExchangeRPCServer) GetFeePayer(context.Context, *GetFeePayerRequest) (*GetFeePayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeePayer not implemented")
}
func (UnimplementedLiquentExchangeRPCServer) mustEmbedUnimplementedLiquentExchangeRPCServer() {}

// UnsafeLiquentExchangeRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiquentExchangeRPCServer will
// result in compilation errors.
type UnsafeLiquentExchangeRPCServer interface {
	mustEmbedUnimplementedLiquentExchangeRPCServer()
}

func RegisterLiquentExchangeRPCServer(s grpc.ServiceRegistrar, srv LiquentExchangeRPCServer) {
	s.RegisterService(&LiquentExchangeRPC_ServiceDesc, srv)
}

func _LiquentExchangeRPC_GetTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExchangeRPCServer).GetTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_exchange_rpc.LiquentExchangeRPC/GetTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExchangeRPCServer).GetTx(ctx, req.(*GetTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExchangeRPC_PrepareTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExchangeRPCServer).PrepareTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_exchange_rpc.LiquentExchangeRPC/PrepareTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExchangeRPCServer).PrepareTx(ctx, req.(*PrepareTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExchangeRPC_PrepareEip712_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareEip712Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExchangeRPCServer).PrepareEip712(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_exchange_rpc.LiquentExchangeRPC/PrepareEip712",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExchangeRPCServer).PrepareEip712(ctx, req.(*PrepareEip712Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExchangeRPC_BroadcastTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExchangeRPCServer).BroadcastTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_exchange_rpc.LiquentExchangeRPC/BroadcastTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExchangeRPCServer).BroadcastTx(ctx, req.(*BroadcastTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExchangeRPC_PrepareCosmosTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareCosmosTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExchangeRPCServer).PrepareCosmosTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_exchange_rpc.LiquentExchangeRPC/PrepareCosmosTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExchangeRPCServer).PrepareCosmosTx(ctx, req.(*PrepareCosmosTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExchangeRPC_BroadcastCosmosTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastCosmosTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExchangeRPCServer).BroadcastCosmosTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_exchange_rpc.LiquentExchangeRPC/BroadcastCosmosTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExchangeRPCServer).BroadcastCosmosTx(ctx, req.(*BroadcastCosmosTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExchangeRPC_GetFeePayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeePayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExchangeRPCServer).GetFeePayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_exchange_rpc.LiquentExchangeRPC/GetFeePayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExchangeRPCServer).GetFeePayer(ctx, req.(*GetFeePayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LiquentExchangeRPC_ServiceDesc is the grpc.ServiceDesc for LiquentExchangeRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiquentExchangeRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "liquent_exchange_rpc.LiquentExchangeRPC",
	HandlerType: (*LiquentExchangeRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTx",
			Handler:    _LiquentExchangeRPC_GetTx_Handler,
		},
		{
			MethodName: "PrepareTx",
			Handler:    _LiquentExchangeRPC_PrepareTx_Handler,
		},
		{
			MethodName: "PrepareEip712",
			Handler:    _LiquentExchangeRPC_PrepareEip712_Handler,
		},
		{
			MethodName: "BroadcastTx",
			Handler:    _LiquentExchangeRPC_BroadcastTx_Handler,
		},
		{
			MethodName: "PrepareCosmosTx",
			Handler:    _LiquentExchangeRPC_PrepareCosmosTx_Handler,
		},
		{
			MethodName: "BroadcastCosmosTx",
			Handler:    _LiquentExchangeRPC_BroadcastCosmosTx_Handler,
		},
		{
			MethodName: "GetFeePayer",
			Handler:    _LiquentExchangeRPC_GetFeePayer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goadesign_goagen_liquent_exchange_rpc.proto",
}
