// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: goadesign_goagen_liquent_trading_rpc.proto

package liquent_trading_rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LiquentTradingRPCClient is the client API for LiquentTradingRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiquentTradingRPCClient interface {
	// Lists all trading strategies
	ListTradingStrategies(ctx context.Context, in *ListTradingStrategiesRequest, opts ...grpc.CallOption) (*ListTradingStrategiesResponse, error)
	// GetStats returns global statistics in the last 24hs
	GetTradingStats(ctx context.Context, in *GetTradingStatsRequest, opts ...grpc.CallOption) (*GetTradingStatsResponse, error)
	// StreamStrategy streams the trading strategies on state change
	StreamStrategy(ctx context.Context, in *StreamStrategyRequest, opts ...grpc.CallOption) (LiquentTradingRPC_StreamStrategyClient, error)
}

type liquentTradingRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewLiquentTradingRPCClient(cc grpc.ClientConnInterface) LiquentTradingRPCClient {
	return &liquentTradingRPCClient{cc}
}

func (c *liquentTradingRPCClient) ListTradingStrategies(ctx context.Context, in *ListTradingStrategiesRequest, opts ...grpc.CallOption) (*ListTradingStrategiesResponse, error) {
	out := new(ListTradingStrategiesResponse)
	err := c.cc.Invoke(ctx, "/liquent_trading_rpc.LiquentTradingRPC/ListTradingStrategies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentTradingRPCClient) GetTradingStats(ctx context.Context, in *GetTradingStatsRequest, opts ...grpc.CallOption) (*GetTradingStatsResponse, error) {
	out := new(GetTradingStatsResponse)
	err := c.cc.Invoke(ctx, "/liquent_trading_rpc.LiquentTradingRPC/GetTradingStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentTradingRPCClient) StreamStrategy(ctx context.Context, in *StreamStrategyRequest, opts ...grpc.CallOption) (LiquentTradingRPC_StreamStrategyClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentTradingRPC_ServiceDesc.Streams[0], "/liquent_trading_rpc.LiquentTradingRPC/StreamStrategy", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentTradingRPCStreamStrategyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentTradingRPC_StreamStrategyClient interface {
	Recv() (*StreamStrategyResponse, error)
	grpc.ClientStream
}

type liquentTradingRPCStreamStrategyClient struct {
	grpc.ClientStream
}

func (x *liquentTradingRPCStreamStrategyClient) Recv() (*StreamStrategyResponse, error) {
	m := new(StreamStrategyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LiquentTradingRPCServer is the server API for LiquentTradingRPC service.
// All implementations must embed UnimplementedLiquentTradingRPCServer
// for forward compatibility
type LiquentTradingRPCServer interface {
	// Lists all trading strategies
	ListTradingStrategies(context.Context, *ListTradingStrategiesRequest) (*ListTradingStrategiesResponse, error)
	// GetStats returns global statistics in the last 24hs
	GetTradingStats(context.Context, *GetTradingStatsRequest) (*GetTradingStatsResponse, error)
	// StreamStrategy streams the trading strategies on state change
	StreamStrategy(*StreamStrategyRequest, LiquentTradingRPC_StreamStrategyServer) error
	mustEmbedUnimplementedLiquentTradingRPCServer()
}

// UnimplementedLiquentTradingRPCServer must be embedded to have forward compatible implementations.
type UnimplementedLiquentTradingRPCServer struct {
}

func (UnimplementedLiquentTradingRPCServer) ListTradingStrategies(context.Context, *ListTradingStrategiesRequest) (*ListTradingStrategiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTradingStrategies not implemented")
}
func (UnimplementedLiquentTradingRPCServer) GetTradingStats(context.Context, *GetTradingStatsRequest) (*GetTradingStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTradingStats not implemented")
}
func (UnimplementedLiquentTradingRPCServer) StreamStrategy(*StreamStrategyRequest, LiquentTradingRPC_StreamStrategyServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamStrategy not implemented")
}
func (UnimplementedLiquentTradingRPCServer) mustEmbedUnimplementedLiquentTradingRPCServer() {}

// UnsafeLiquentTradingRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiquentTradingRPCServer will
// result in compilation errors.
type UnsafeLiquentTradingRPCServer interface {
	mustEmbedUnimplementedLiquentTradingRPCServer()
}

func RegisterLiquentTradingRPCServer(s grpc.ServiceRegistrar, srv LiquentTradingRPCServer) {
	s.RegisterService(&LiquentTradingRPC_ServiceDesc, srv)
}

func _LiquentTradingRPC_ListTradingStrategies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTradingStrategiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentTradingRPCServer).ListTradingStrategies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_trading_rpc.LiquentTradingRPC/ListTradingStrategies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentTradingRPCServer).ListTradingStrategies(ctx, req.(*ListTradingStrategiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentTradingRPC_GetTradingStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTradingStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentTradingRPCServer).GetTradingStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_trading_rpc.LiquentTradingRPC/GetTradingStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentTradingRPCServer).GetTradingStats(ctx, req.(*GetTradingStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentTradingRPC_StreamStrategy_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamStrategyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentTradingRPCServer).StreamStrategy(m, &liquentTradingRPCStreamStrategyServer{stream})
}

type LiquentTradingRPC_StreamStrategyServer interface {
	Send(*StreamStrategyResponse) error
	grpc.ServerStream
}

type liquentTradingRPCStreamStrategyServer struct {
	grpc.ServerStream
}

func (x *liquentTradingRPCStreamStrategyServer) Send(m *StreamStrategyResponse) error {
	return x.ServerStream.SendMsg(m)
}

// LiquentTradingRPC_ServiceDesc is the grpc.ServiceDesc for LiquentTradingRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiquentTradingRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "liquent_trading_rpc.LiquentTradingRPC",
	HandlerType: (*LiquentTradingRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTradingStrategies",
			Handler:    _LiquentTradingRPC_ListTradingStrategies_Handler,
		},
		{
			MethodName: "GetTradingStats",
			Handler:    _LiquentTradingRPC_GetTradingStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamStrategy",
			Handler:       _LiquentTradingRPC_StreamStrategy_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "goadesign_goagen_liquent_trading_rpc.proto",
}
