// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: goadesign_goagen_liquent_accounts_rpc.proto

package liquent_accounts_rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LiquentAccountsRPCClient is the client API for LiquentAccountsRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiquentAccountsRPCClient interface {
	// Provide the account's portfolio value in USD.
	Portfolio(ctx context.Context, in *PortfolioRequest, opts ...grpc.CallOption) (*PortfolioResponse, error)
	// List order states by order hashes
	OrderStates(ctx context.Context, in *OrderStatesRequest, opts ...grpc.CallOption) (*OrderStatesResponse, error)
	// List all subaccounts IDs of an account address
	SubaccountsList(ctx context.Context, in *SubaccountsListRequest, opts ...grpc.CallOption) (*SubaccountsListResponse, error)
	// List subaccount balances for the provided denoms.
	SubaccountBalancesList(ctx context.Context, in *SubaccountBalancesListRequest, opts ...grpc.CallOption) (*SubaccountBalancesListResponse, error)
	// Gets a balance for specific coin denom
	SubaccountBalanceEndpoint(ctx context.Context, in *SubaccountBalanceEndpointRequest, opts ...grpc.CallOption) (*SubaccountBalanceEndpointResponse, error)
	// StreamSubaccountBalance streams new balance changes for a specified
	// subaccount and denoms. If no denoms are provided, all denom changes are
	// streamed.
	StreamSubaccountBalance(ctx context.Context, in *StreamSubaccountBalanceRequest, opts ...grpc.CallOption) (LiquentAccountsRPC_StreamSubaccountBalanceClient, error)
	// Get subaccount's deposits and withdrawals history
	SubaccountHistory(ctx context.Context, in *SubaccountHistoryRequest, opts ...grpc.CallOption) (*SubaccountHistoryResponse, error)
	// Get subaccount's orders summary
	SubaccountOrderSummary(ctx context.Context, in *SubaccountOrderSummaryRequest, opts ...grpc.CallOption) (*SubaccountOrderSummaryResponse, error)
	// Provide historical trading rewards
	Rewards(ctx context.Context, in *RewardsRequest, opts ...grpc.CallOption) (*RewardsResponse, error)
	// Stream live data for an account and respective data
	StreamAccountData(ctx context.Context, in *StreamAccountDataRequest, opts ...grpc.CallOption) (LiquentAccountsRPC_StreamAccountDataClient, error)
}

type liquentAccountsRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewLiquentAccountsRPCClient(cc grpc.ClientConnInterface) LiquentAccountsRPCClient {
	return &liquentAccountsRPCClient{cc}
}

func (c *liquentAccountsRPCClient) Portfolio(ctx context.Context, in *PortfolioRequest, opts ...grpc.CallOption) (*PortfolioResponse, error) {
	out := new(PortfolioResponse)
	err := c.cc.Invoke(ctx, "/liquent_accounts_rpc.LiquentAccountsRPC/Portfolio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentAccountsRPCClient) OrderStates(ctx context.Context, in *OrderStatesRequest, opts ...grpc.CallOption) (*OrderStatesResponse, error) {
	out := new(OrderStatesResponse)
	err := c.cc.Invoke(ctx, "/liquent_accounts_rpc.LiquentAccountsRPC/OrderStates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentAccountsRPCClient) SubaccountsList(ctx context.Context, in *SubaccountsListRequest, opts ...grpc.CallOption) (*SubaccountsListResponse, error) {
	out := new(SubaccountsListResponse)
	err := c.cc.Invoke(ctx, "/liquent_accounts_rpc.LiquentAccountsRPC/SubaccountsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentAccountsRPCClient) SubaccountBalancesList(ctx context.Context, in *SubaccountBalancesListRequest, opts ...grpc.CallOption) (*SubaccountBalancesListResponse, error) {
	out := new(SubaccountBalancesListResponse)
	err := c.cc.Invoke(ctx, "/liquent_accounts_rpc.LiquentAccountsRPC/SubaccountBalancesList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentAccountsRPCClient) SubaccountBalanceEndpoint(ctx context.Context, in *SubaccountBalanceEndpointRequest, opts ...grpc.CallOption) (*SubaccountBalanceEndpointResponse, error) {
	out := new(SubaccountBalanceEndpointResponse)
	err := c.cc.Invoke(ctx, "/liquent_accounts_rpc.LiquentAccountsRPC/SubaccountBalanceEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentAccountsRPCClient) StreamSubaccountBalance(ctx context.Context, in *StreamSubaccountBalanceRequest, opts ...grpc.CallOption) (LiquentAccountsRPC_StreamSubaccountBalanceClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentAccountsRPC_ServiceDesc.Streams[0], "/liquent_accounts_rpc.LiquentAccountsRPC/StreamSubaccountBalance", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentAccountsRPCStreamSubaccountBalanceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentAccountsRPC_StreamSubaccountBalanceClient interface {
	Recv() (*StreamSubaccountBalanceResponse, error)
	grpc.ClientStream
}

type liquentAccountsRPCStreamSubaccountBalanceClient struct {
	grpc.ClientStream
}

func (x *liquentAccountsRPCStreamSubaccountBalanceClient) Recv() (*StreamSubaccountBalanceResponse, error) {
	m := new(StreamSubaccountBalanceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentAccountsRPCClient) SubaccountHistory(ctx context.Context, in *SubaccountHistoryRequest, opts ...grpc.CallOption) (*SubaccountHistoryResponse, error) {
	out := new(SubaccountHistoryResponse)
	err := c.cc.Invoke(ctx, "/liquent_accounts_rpc.LiquentAccountsRPC/SubaccountHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentAccountsRPCClient) SubaccountOrderSummary(ctx context.Context, in *SubaccountOrderSummaryRequest, opts ...grpc.CallOption) (*SubaccountOrderSummaryResponse, error) {
	out := new(SubaccountOrderSummaryResponse)
	err := c.cc.Invoke(ctx, "/liquent_accounts_rpc.LiquentAccountsRPC/SubaccountOrderSummary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentAccountsRPCClient) Rewards(ctx context.Context, in *RewardsRequest, opts ...grpc.CallOption) (*RewardsResponse, error) {
	out := new(RewardsResponse)
	err := c.cc.Invoke(ctx, "/liquent_accounts_rpc.LiquentAccountsRPC/Rewards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentAccountsRPCClient) StreamAccountData(ctx context.Context, in *StreamAccountDataRequest, opts ...grpc.CallOption) (LiquentAccountsRPC_StreamAccountDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentAccountsRPC_ServiceDesc.Streams[1], "/liquent_accounts_rpc.LiquentAccountsRPC/StreamAccountData", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentAccountsRPCStreamAccountDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentAccountsRPC_StreamAccountDataClient interface {
	Recv() (*StreamAccountDataResponse, error)
	grpc.ClientStream
}

type liquentAccountsRPCStreamAccountDataClient struct {
	grpc.ClientStream
}

func (x *liquentAccountsRPCStreamAccountDataClient) Recv() (*StreamAccountDataResponse, error) {
	m := new(StreamAccountDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LiquentAccountsRPCServer is the server API for LiquentAccountsRPC service.
// All implementations must embed UnimplementedLiquentAccountsRPCServer
// for forward compatibility
type LiquentAccountsRPCServer interface {
	// Provide the account's portfolio value in USD.
	Portfolio(context.Context, *PortfolioRequest) (*PortfolioResponse, error)
	// List order states by order hashes
	OrderStates(context.Context, *OrderStatesRequest) (*OrderStatesResponse, error)
	// List all subaccounts IDs of an account address
	SubaccountsList(context.Context, *SubaccountsListRequest) (*SubaccountsListResponse, error)
	// List subaccount balances for the provided denoms.
	SubaccountBalancesList(context.Context, *SubaccountBalancesListRequest) (*SubaccountBalancesListResponse, error)
	// Gets a balance for specific coin denom
	SubaccountBalanceEndpoint(context.Context, *SubaccountBalanceEndpointRequest) (*SubaccountBalanceEndpointResponse, error)
	// StreamSubaccountBalance streams new balance changes for a specified
	// subaccount and denoms. If no denoms are provided, all denom changes are
	// streamed.
	StreamSubaccountBalance(*StreamSubaccountBalanceRequest, LiquentAccountsRPC_StreamSubaccountBalanceServer) error
	// Get subaccount's deposits and withdrawals history
	SubaccountHistory(context.Context, *SubaccountHistoryRequest) (*SubaccountHistoryResponse, error)
	// Get subaccount's orders summary
	SubaccountOrderSummary(context.Context, *SubaccountOrderSummaryRequest) (*SubaccountOrderSummaryResponse, error)
	// Provide historical trading rewards
	Rewards(context.Context, *RewardsRequest) (*RewardsResponse, error)
	// Stream live data for an account and respective data
	StreamAccountData(*StreamAccountDataRequest, LiquentAccountsRPC_StreamAccountDataServer) error
	mustEmbedUnimplementedLiquentAccountsRPCServer()
}

// UnimplementedLiquentAccountsRPCServer must be embedded to have forward compatible implementations.
type UnimplementedLiquentAccountsRPCServer struct {
}

func (UnimplementedLiquentAccountsRPCServer) Portfolio(context.Context, *PortfolioRequest) (*PortfolioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Portfolio not implemented")
}
func (UnimplementedLiquentAccountsRPCServer) OrderStates(context.Context, *OrderStatesRequest) (*OrderStatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderStates not implemented")
}
func (UnimplementedLiquentAccountsRPCServer) SubaccountsList(context.Context, *SubaccountsListRequest) (*SubaccountsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubaccountsList not implemented")
}
func (UnimplementedLiquentAccountsRPCServer) SubaccountBalancesList(context.Context, *SubaccountBalancesListRequest) (*SubaccountBalancesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubaccountBalancesList not implemented")
}
func (UnimplementedLiquentAccountsRPCServer) SubaccountBalanceEndpoint(context.Context, *SubaccountBalanceEndpointRequest) (*SubaccountBalanceEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubaccountBalanceEndpoint not implemented")
}
func (UnimplementedLiquentAccountsRPCServer) StreamSubaccountBalance(*StreamSubaccountBalanceRequest, LiquentAccountsRPC_StreamSubaccountBalanceServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamSubaccountBalance not implemented")
}
func (UnimplementedLiquentAccountsRPCServer) SubaccountHistory(context.Context, *SubaccountHistoryRequest) (*SubaccountHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubaccountHistory not implemented")
}
func (UnimplementedLiquentAccountsRPCServer) SubaccountOrderSummary(context.Context, *SubaccountOrderSummaryRequest) (*SubaccountOrderSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubaccountOrderSummary not implemented")
}
func (UnimplementedLiquentAccountsRPCServer) Rewards(context.Context, *RewardsRequest) (*RewardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rewards not implemented")
}
func (UnimplementedLiquentAccountsRPCServer) StreamAccountData(*StreamAccountDataRequest, LiquentAccountsRPC_StreamAccountDataServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAccountData not implemented")
}
func (UnimplementedLiquentAccountsRPCServer) mustEmbedUnimplementedLiquentAccountsRPCServer() {}

// UnsafeLiquentAccountsRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiquentAccountsRPCServer will
// result in compilation errors.
type UnsafeLiquentAccountsRPCServer interface {
	mustEmbedUnimplementedLiquentAccountsRPCServer()
}

func RegisterLiquentAccountsRPCServer(s grpc.ServiceRegistrar, srv LiquentAccountsRPCServer) {
	s.RegisterService(&LiquentAccountsRPC_ServiceDesc, srv)
}

func _LiquentAccountsRPC_Portfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortfolioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentAccountsRPCServer).Portfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_accounts_rpc.LiquentAccountsRPC/Portfolio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentAccountsRPCServer).Portfolio(ctx, req.(*PortfolioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentAccountsRPC_OrderStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentAccountsRPCServer).OrderStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_accounts_rpc.LiquentAccountsRPC/OrderStates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentAccountsRPCServer).OrderStates(ctx, req.(*OrderStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentAccountsRPC_SubaccountsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubaccountsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentAccountsRPCServer).SubaccountsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_accounts_rpc.LiquentAccountsRPC/SubaccountsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentAccountsRPCServer).SubaccountsList(ctx, req.(*SubaccountsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentAccountsRPC_SubaccountBalancesList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubaccountBalancesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentAccountsRPCServer).SubaccountBalancesList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_accounts_rpc.LiquentAccountsRPC/SubaccountBalancesList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentAccountsRPCServer).SubaccountBalancesList(ctx, req.(*SubaccountBalancesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentAccountsRPC_SubaccountBalanceEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubaccountBalanceEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentAccountsRPCServer).SubaccountBalanceEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_accounts_rpc.LiquentAccountsRPC/SubaccountBalanceEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentAccountsRPCServer).SubaccountBalanceEndpoint(ctx, req.(*SubaccountBalanceEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentAccountsRPC_StreamSubaccountBalance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSubaccountBalanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentAccountsRPCServer).StreamSubaccountBalance(m, &liquentAccountsRPCStreamSubaccountBalanceServer{stream})
}

type LiquentAccountsRPC_StreamSubaccountBalanceServer interface {
	Send(*StreamSubaccountBalanceResponse) error
	grpc.ServerStream
}

type liquentAccountsRPCStreamSubaccountBalanceServer struct {
	grpc.ServerStream
}

func (x *liquentAccountsRPCStreamSubaccountBalanceServer) Send(m *StreamSubaccountBalanceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentAccountsRPC_SubaccountHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubaccountHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentAccountsRPCServer).SubaccountHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_accounts_rpc.LiquentAccountsRPC/SubaccountHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentAccountsRPCServer).SubaccountHistory(ctx, req.(*SubaccountHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentAccountsRPC_SubaccountOrderSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubaccountOrderSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentAccountsRPCServer).SubaccountOrderSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_accounts_rpc.LiquentAccountsRPC/SubaccountOrderSummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentAccountsRPCServer).SubaccountOrderSummary(ctx, req.(*SubaccountOrderSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentAccountsRPC_Rewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentAccountsRPCServer).Rewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_accounts_rpc.LiquentAccountsRPC/Rewards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentAccountsRPCServer).Rewards(ctx, req.(*RewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentAccountsRPC_StreamAccountData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAccountDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentAccountsRPCServer).StreamAccountData(m, &liquentAccountsRPCStreamAccountDataServer{stream})
}

type LiquentAccountsRPC_StreamAccountDataServer interface {
	Send(*StreamAccountDataResponse) error
	grpc.ServerStream
}

type liquentAccountsRPCStreamAccountDataServer struct {
	grpc.ServerStream
}

func (x *liquentAccountsRPCStreamAccountDataServer) Send(m *StreamAccountDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

// LiquentAccountsRPC_ServiceDesc is the grpc.ServiceDesc for LiquentAccountsRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiquentAccountsRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "liquent_accounts_rpc.LiquentAccountsRPC",
	HandlerType: (*LiquentAccountsRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Portfolio",
			Handler:    _LiquentAccountsRPC_Portfolio_Handler,
		},
		{
			MethodName: "OrderStates",
			Handler:    _LiquentAccountsRPC_OrderStates_Handler,
		},
		{
			MethodName: "SubaccountsList",
			Handler:    _LiquentAccountsRPC_SubaccountsList_Handler,
		},
		{
			MethodName: "SubaccountBalancesList",
			Handler:    _LiquentAccountsRPC_SubaccountBalancesList_Handler,
		},
		{
			MethodName: "SubaccountBalanceEndpoint",
			Handler:    _LiquentAccountsRPC_SubaccountBalanceEndpoint_Handler,
		},
		{
			MethodName: "SubaccountHistory",
			Handler:    _LiquentAccountsRPC_SubaccountHistory_Handler,
		},
		{
			MethodName: "SubaccountOrderSummary",
			Handler:    _LiquentAccountsRPC_SubaccountOrderSummary_Handler,
		},
		{
			MethodName: "Rewards",
			Handler:    _LiquentAccountsRPC_Rewards_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSubaccountBalance",
			Handler:       _LiquentAccountsRPC_StreamSubaccountBalance_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamAccountData",
			Handler:       _LiquentAccountsRPC_StreamAccountData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "goadesign_goagen_liquent_accounts_rpc.proto",
}
