// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: goadesign_goagen_liquent_spot_exchange_rpc.proto

package liquent_spot_exchange_rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LiquentSpotExchangeRPCClient is the client API for LiquentSpotExchangeRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiquentSpotExchangeRPCClient interface {
	// Get a list of Spot Markets
	Markets(ctx context.Context, in *MarketsRequest, opts ...grpc.CallOption) (*MarketsResponse, error)
	// Get details of a single spot market
	Market(ctx context.Context, in *MarketRequest, opts ...grpc.CallOption) (*MarketResponse, error)
	// Stream live updates of selected spot markets
	StreamMarkets(ctx context.Context, in *StreamMarketsRequest, opts ...grpc.CallOption) (LiquentSpotExchangeRPC_StreamMarketsClient, error)
	// Orderbook of a Spot Market
	OrderbookV2(ctx context.Context, in *OrderbookV2Request, opts ...grpc.CallOption) (*OrderbookV2Response, error)
	// Orderbook of Spot Markets
	OrderbooksV2(ctx context.Context, in *OrderbooksV2Request, opts ...grpc.CallOption) (*OrderbooksV2Response, error)
	// Stream live snapshot updates of selected spot market orderbook
	StreamOrderbookV2(ctx context.Context, in *StreamOrderbookV2Request, opts ...grpc.CallOption) (LiquentSpotExchangeRPC_StreamOrderbookV2Client, error)
	// Stream live level updates of selected spot market orderbook
	StreamOrderbookUpdate(ctx context.Context, in *StreamOrderbookUpdateRequest, opts ...grpc.CallOption) (LiquentSpotExchangeRPC_StreamOrderbookUpdateClient, error)
	// Orders of a Spot Market
	Orders(ctx context.Context, in *OrdersRequest, opts ...grpc.CallOption) (*OrdersResponse, error)
	// Stream updates to individual orders of a Spot Market
	StreamOrders(ctx context.Context, in *StreamOrdersRequest, opts ...grpc.CallOption) (LiquentSpotExchangeRPC_StreamOrdersClient, error)
	// Trades of a Spot Market
	Trades(ctx context.Context, in *TradesRequest, opts ...grpc.CallOption) (*TradesResponse, error)
	// Stream newly executed trades from Spot Market
	StreamTrades(ctx context.Context, in *StreamTradesRequest, opts ...grpc.CallOption) (LiquentSpotExchangeRPC_StreamTradesClient, error)
	// Trades of a Spot Market
	TradesV2(ctx context.Context, in *TradesV2Request, opts ...grpc.CallOption) (*TradesV2Response, error)
	// Stream newly executed trades from Spot Market
	StreamTradesV2(ctx context.Context, in *StreamTradesV2Request, opts ...grpc.CallOption) (LiquentSpotExchangeRPC_StreamTradesV2Client, error)
	// List orders posted from this subaccount
	SubaccountOrdersList(ctx context.Context, in *SubaccountOrdersListRequest, opts ...grpc.CallOption) (*SubaccountOrdersListResponse, error)
	// List trades executed by this subaccount
	SubaccountTradesList(ctx context.Context, in *SubaccountTradesListRequest, opts ...grpc.CallOption) (*SubaccountTradesListResponse, error)
	// Lists history orders posted from this subaccount
	OrdersHistory(ctx context.Context, in *OrdersHistoryRequest, opts ...grpc.CallOption) (*OrdersHistoryResponse, error)
	// Stream updates to historical orders of a spot Market
	StreamOrdersHistory(ctx context.Context, in *StreamOrdersHistoryRequest, opts ...grpc.CallOption) (LiquentSpotExchangeRPC_StreamOrdersHistoryClient, error)
	// Get historical atomic swaps
	AtomicSwapHistory(ctx context.Context, in *AtomicSwapHistoryRequest, opts ...grpc.CallOption) (*AtomicSwapHistoryResponse, error)
}

type liquentSpotExchangeRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewLiquentSpotExchangeRPCClient(cc grpc.ClientConnInterface) LiquentSpotExchangeRPCClient {
	return &liquentSpotExchangeRPCClient{cc}
}

func (c *liquentSpotExchangeRPCClient) Markets(ctx context.Context, in *MarketsRequest, opts ...grpc.CallOption) (*MarketsResponse, error) {
	out := new(MarketsResponse)
	err := c.cc.Invoke(ctx, "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/Markets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentSpotExchangeRPCClient) Market(ctx context.Context, in *MarketRequest, opts ...grpc.CallOption) (*MarketResponse, error) {
	out := new(MarketResponse)
	err := c.cc.Invoke(ctx, "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/Market", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentSpotExchangeRPCClient) StreamMarkets(ctx context.Context, in *StreamMarketsRequest, opts ...grpc.CallOption) (LiquentSpotExchangeRPC_StreamMarketsClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentSpotExchangeRPC_ServiceDesc.Streams[0], "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/StreamMarkets", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentSpotExchangeRPCStreamMarketsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentSpotExchangeRPC_StreamMarketsClient interface {
	Recv() (*StreamMarketsResponse, error)
	grpc.ClientStream
}

type liquentSpotExchangeRPCStreamMarketsClient struct {
	grpc.ClientStream
}

func (x *liquentSpotExchangeRPCStreamMarketsClient) Recv() (*StreamMarketsResponse, error) {
	m := new(StreamMarketsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentSpotExchangeRPCClient) OrderbookV2(ctx context.Context, in *OrderbookV2Request, opts ...grpc.CallOption) (*OrderbookV2Response, error) {
	out := new(OrderbookV2Response)
	err := c.cc.Invoke(ctx, "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/OrderbookV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentSpotExchangeRPCClient) OrderbooksV2(ctx context.Context, in *OrderbooksV2Request, opts ...grpc.CallOption) (*OrderbooksV2Response, error) {
	out := new(OrderbooksV2Response)
	err := c.cc.Invoke(ctx, "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/OrderbooksV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentSpotExchangeRPCClient) StreamOrderbookV2(ctx context.Context, in *StreamOrderbookV2Request, opts ...grpc.CallOption) (LiquentSpotExchangeRPC_StreamOrderbookV2Client, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentSpotExchangeRPC_ServiceDesc.Streams[1], "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/StreamOrderbookV2", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentSpotExchangeRPCStreamOrderbookV2Client{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentSpotExchangeRPC_StreamOrderbookV2Client interface {
	Recv() (*StreamOrderbookV2Response, error)
	grpc.ClientStream
}

type liquentSpotExchangeRPCStreamOrderbookV2Client struct {
	grpc.ClientStream
}

func (x *liquentSpotExchangeRPCStreamOrderbookV2Client) Recv() (*StreamOrderbookV2Response, error) {
	m := new(StreamOrderbookV2Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentSpotExchangeRPCClient) StreamOrderbookUpdate(ctx context.Context, in *StreamOrderbookUpdateRequest, opts ...grpc.CallOption) (LiquentSpotExchangeRPC_StreamOrderbookUpdateClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentSpotExchangeRPC_ServiceDesc.Streams[2], "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/StreamOrderbookUpdate", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentSpotExchangeRPCStreamOrderbookUpdateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentSpotExchangeRPC_StreamOrderbookUpdateClient interface {
	Recv() (*StreamOrderbookUpdateResponse, error)
	grpc.ClientStream
}

type liquentSpotExchangeRPCStreamOrderbookUpdateClient struct {
	grpc.ClientStream
}

func (x *liquentSpotExchangeRPCStreamOrderbookUpdateClient) Recv() (*StreamOrderbookUpdateResponse, error) {
	m := new(StreamOrderbookUpdateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentSpotExchangeRPCClient) Orders(ctx context.Context, in *OrdersRequest, opts ...grpc.CallOption) (*OrdersResponse, error) {
	out := new(OrdersResponse)
	err := c.cc.Invoke(ctx, "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/Orders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentSpotExchangeRPCClient) StreamOrders(ctx context.Context, in *StreamOrdersRequest, opts ...grpc.CallOption) (LiquentSpotExchangeRPC_StreamOrdersClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentSpotExchangeRPC_ServiceDesc.Streams[3], "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/StreamOrders", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentSpotExchangeRPCStreamOrdersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentSpotExchangeRPC_StreamOrdersClient interface {
	Recv() (*StreamOrdersResponse, error)
	grpc.ClientStream
}

type liquentSpotExchangeRPCStreamOrdersClient struct {
	grpc.ClientStream
}

func (x *liquentSpotExchangeRPCStreamOrdersClient) Recv() (*StreamOrdersResponse, error) {
	m := new(StreamOrdersResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentSpotExchangeRPCClient) Trades(ctx context.Context, in *TradesRequest, opts ...grpc.CallOption) (*TradesResponse, error) {
	out := new(TradesResponse)
	err := c.cc.Invoke(ctx, "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/Trades", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentSpotExchangeRPCClient) StreamTrades(ctx context.Context, in *StreamTradesRequest, opts ...grpc.CallOption) (LiquentSpotExchangeRPC_StreamTradesClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentSpotExchangeRPC_ServiceDesc.Streams[4], "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/StreamTrades", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentSpotExchangeRPCStreamTradesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentSpotExchangeRPC_StreamTradesClient interface {
	Recv() (*StreamTradesResponse, error)
	grpc.ClientStream
}

type liquentSpotExchangeRPCStreamTradesClient struct {
	grpc.ClientStream
}

func (x *liquentSpotExchangeRPCStreamTradesClient) Recv() (*StreamTradesResponse, error) {
	m := new(StreamTradesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentSpotExchangeRPCClient) TradesV2(ctx context.Context, in *TradesV2Request, opts ...grpc.CallOption) (*TradesV2Response, error) {
	out := new(TradesV2Response)
	err := c.cc.Invoke(ctx, "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/TradesV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentSpotExchangeRPCClient) StreamTradesV2(ctx context.Context, in *StreamTradesV2Request, opts ...grpc.CallOption) (LiquentSpotExchangeRPC_StreamTradesV2Client, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentSpotExchangeRPC_ServiceDesc.Streams[5], "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/StreamTradesV2", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentSpotExchangeRPCStreamTradesV2Client{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentSpotExchangeRPC_StreamTradesV2Client interface {
	Recv() (*StreamTradesV2Response, error)
	grpc.ClientStream
}

type liquentSpotExchangeRPCStreamTradesV2Client struct {
	grpc.ClientStream
}

func (x *liquentSpotExchangeRPCStreamTradesV2Client) Recv() (*StreamTradesV2Response, error) {
	m := new(StreamTradesV2Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentSpotExchangeRPCClient) SubaccountOrdersList(ctx context.Context, in *SubaccountOrdersListRequest, opts ...grpc.CallOption) (*SubaccountOrdersListResponse, error) {
	out := new(SubaccountOrdersListResponse)
	err := c.cc.Invoke(ctx, "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/SubaccountOrdersList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentSpotExchangeRPCClient) SubaccountTradesList(ctx context.Context, in *SubaccountTradesListRequest, opts ...grpc.CallOption) (*SubaccountTradesListResponse, error) {
	out := new(SubaccountTradesListResponse)
	err := c.cc.Invoke(ctx, "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/SubaccountTradesList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentSpotExchangeRPCClient) OrdersHistory(ctx context.Context, in *OrdersHistoryRequest, opts ...grpc.CallOption) (*OrdersHistoryResponse, error) {
	out := new(OrdersHistoryResponse)
	err := c.cc.Invoke(ctx, "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/OrdersHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentSpotExchangeRPCClient) StreamOrdersHistory(ctx context.Context, in *StreamOrdersHistoryRequest, opts ...grpc.CallOption) (LiquentSpotExchangeRPC_StreamOrdersHistoryClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentSpotExchangeRPC_ServiceDesc.Streams[6], "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/StreamOrdersHistory", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentSpotExchangeRPCStreamOrdersHistoryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentSpotExchangeRPC_StreamOrdersHistoryClient interface {
	Recv() (*StreamOrdersHistoryResponse, error)
	grpc.ClientStream
}

type liquentSpotExchangeRPCStreamOrdersHistoryClient struct {
	grpc.ClientStream
}

func (x *liquentSpotExchangeRPCStreamOrdersHistoryClient) Recv() (*StreamOrdersHistoryResponse, error) {
	m := new(StreamOrdersHistoryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentSpotExchangeRPCClient) AtomicSwapHistory(ctx context.Context, in *AtomicSwapHistoryRequest, opts ...grpc.CallOption) (*AtomicSwapHistoryResponse, error) {
	out := new(AtomicSwapHistoryResponse)
	err := c.cc.Invoke(ctx, "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/AtomicSwapHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiquentSpotExchangeRPCServer is the server API for LiquentSpotExchangeRPC service.
// All implementations must embed UnimplementedLiquentSpotExchangeRPCServer
// for forward compatibility
type LiquentSpotExchangeRPCServer interface {
	// Get a list of Spot Markets
	Markets(context.Context, *MarketsRequest) (*MarketsResponse, error)
	// Get details of a single spot market
	Market(context.Context, *MarketRequest) (*MarketResponse, error)
	// Stream live updates of selected spot markets
	StreamMarkets(*StreamMarketsRequest, LiquentSpotExchangeRPC_StreamMarketsServer) error
	// Orderbook of a Spot Market
	OrderbookV2(context.Context, *OrderbookV2Request) (*OrderbookV2Response, error)
	// Orderbook of Spot Markets
	OrderbooksV2(context.Context, *OrderbooksV2Request) (*OrderbooksV2Response, error)
	// Stream live snapshot updates of selected spot market orderbook
	StreamOrderbookV2(*StreamOrderbookV2Request, LiquentSpotExchangeRPC_StreamOrderbookV2Server) error
	// Stream live level updates of selected spot market orderbook
	StreamOrderbookUpdate(*StreamOrderbookUpdateRequest, LiquentSpotExchangeRPC_StreamOrderbookUpdateServer) error
	// Orders of a Spot Market
	Orders(context.Context, *OrdersRequest) (*OrdersResponse, error)
	// Stream updates to individual orders of a Spot Market
	StreamOrders(*StreamOrdersRequest, LiquentSpotExchangeRPC_StreamOrdersServer) error
	// Trades of a Spot Market
	Trades(context.Context, *TradesRequest) (*TradesResponse, error)
	// Stream newly executed trades from Spot Market
	StreamTrades(*StreamTradesRequest, LiquentSpotExchangeRPC_StreamTradesServer) error
	// Trades of a Spot Market
	TradesV2(context.Context, *TradesV2Request) (*TradesV2Response, error)
	// Stream newly executed trades from Spot Market
	StreamTradesV2(*StreamTradesV2Request, LiquentSpotExchangeRPC_StreamTradesV2Server) error
	// List orders posted from this subaccount
	SubaccountOrdersList(context.Context, *SubaccountOrdersListRequest) (*SubaccountOrdersListResponse, error)
	// List trades executed by this subaccount
	SubaccountTradesList(context.Context, *SubaccountTradesListRequest) (*SubaccountTradesListResponse, error)
	// Lists history orders posted from this subaccount
	OrdersHistory(context.Context, *OrdersHistoryRequest) (*OrdersHistoryResponse, error)
	// Stream updates to historical orders of a spot Market
	StreamOrdersHistory(*StreamOrdersHistoryRequest, LiquentSpotExchangeRPC_StreamOrdersHistoryServer) error
	// Get historical atomic swaps
	AtomicSwapHistory(context.Context, *AtomicSwapHistoryRequest) (*AtomicSwapHistoryResponse, error)
	mustEmbedUnimplementedLiquentSpotExchangeRPCServer()
}

// UnimplementedLiquentSpotExchangeRPCServer must be embedded to have forward compatible implementations.
type UnimplementedLiquentSpotExchangeRPCServer struct {
}

func (UnimplementedLiquentSpotExchangeRPCServer) Markets(context.Context, *MarketsRequest) (*MarketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Markets not implemented")
}
func (UnimplementedLiquentSpotExchangeRPCServer) Market(context.Context, *MarketRequest) (*MarketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Market not implemented")
}
func (UnimplementedLiquentSpotExchangeRPCServer) StreamMarkets(*StreamMarketsRequest, LiquentSpotExchangeRPC_StreamMarketsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMarkets not implemented")
}
func (UnimplementedLiquentSpotExchangeRPCServer) OrderbookV2(context.Context, *OrderbookV2Request) (*OrderbookV2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderbookV2 not implemented")
}
func (UnimplementedLiquentSpotExchangeRPCServer) OrderbooksV2(context.Context, *OrderbooksV2Request) (*OrderbooksV2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderbooksV2 not implemented")
}
func (UnimplementedLiquentSpotExchangeRPCServer) StreamOrderbookV2(*StreamOrderbookV2Request, LiquentSpotExchangeRPC_StreamOrderbookV2Server) error {
	return status.Errorf(codes.Unimplemented, "method StreamOrderbookV2 not implemented")
}
func (UnimplementedLiquentSpotExchangeRPCServer) StreamOrderbookUpdate(*StreamOrderbookUpdateRequest, LiquentSpotExchangeRPC_StreamOrderbookUpdateServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamOrderbookUpdate not implemented")
}
func (UnimplementedLiquentSpotExchangeRPCServer) Orders(context.Context, *OrdersRequest) (*OrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Orders not implemented")
}
func (UnimplementedLiquentSpotExchangeRPCServer) StreamOrders(*StreamOrdersRequest, LiquentSpotExchangeRPC_StreamOrdersServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamOrders not implemented")
}
func (UnimplementedLiquentSpotExchangeRPCServer) Trades(context.Context, *TradesRequest) (*TradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Trades not implemented")
}
func (UnimplementedLiquentSpotExchangeRPCServer) StreamTrades(*StreamTradesRequest, LiquentSpotExchangeRPC_StreamTradesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamTrades not implemented")
}
func (UnimplementedLiquentSpotExchangeRPCServer) TradesV2(context.Context, *TradesV2Request) (*TradesV2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TradesV2 not implemented")
}
func (UnimplementedLiquentSpotExchangeRPCServer) StreamTradesV2(*StreamTradesV2Request, LiquentSpotExchangeRPC_StreamTradesV2Server) error {
	return status.Errorf(codes.Unimplemented, "method StreamTradesV2 not implemented")
}
func (UnimplementedLiquentSpotExchangeRPCServer) SubaccountOrdersList(context.Context, *SubaccountOrdersListRequest) (*SubaccountOrdersListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubaccountOrdersList not implemented")
}
func (UnimplementedLiquentSpotExchangeRPCServer) SubaccountTradesList(context.Context, *SubaccountTradesListRequest) (*SubaccountTradesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubaccountTradesList not implemented")
}
func (UnimplementedLiquentSpotExchangeRPCServer) OrdersHistory(context.Context, *OrdersHistoryRequest) (*OrdersHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrdersHistory not implemented")
}
func (UnimplementedLiquentSpotExchangeRPCServer) StreamOrdersHistory(*StreamOrdersHistoryRequest, LiquentSpotExchangeRPC_StreamOrdersHistoryServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamOrdersHistory not implemented")
}
func (UnimplementedLiquentSpotExchangeRPCServer) AtomicSwapHistory(context.Context, *AtomicSwapHistoryRequest) (*AtomicSwapHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AtomicSwapHistory not implemented")
}
func (UnimplementedLiquentSpotExchangeRPCServer) mustEmbedUnimplementedLiquentSpotExchangeRPCServer() {
}

// UnsafeLiquentSpotExchangeRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiquentSpotExchangeRPCServer will
// result in compilation errors.
type UnsafeLiquentSpotExchangeRPCServer interface {
	mustEmbedUnimplementedLiquentSpotExchangeRPCServer()
}

func RegisterLiquentSpotExchangeRPCServer(s grpc.ServiceRegistrar, srv LiquentSpotExchangeRPCServer) {
	s.RegisterService(&LiquentSpotExchangeRPC_ServiceDesc, srv)
}

func _LiquentSpotExchangeRPC_Markets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentSpotExchangeRPCServer).Markets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/Markets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentSpotExchangeRPCServer).Markets(ctx, req.(*MarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentSpotExchangeRPC_Market_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentSpotExchangeRPCServer).Market(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/Market",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentSpotExchangeRPCServer).Market(ctx, req.(*MarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentSpotExchangeRPC_StreamMarkets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMarketsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentSpotExchangeRPCServer).StreamMarkets(m, &liquentSpotExchangeRPCStreamMarketsServer{stream})
}

type LiquentSpotExchangeRPC_StreamMarketsServer interface {
	Send(*StreamMarketsResponse) error
	grpc.ServerStream
}

type liquentSpotExchangeRPCStreamMarketsServer struct {
	grpc.ServerStream
}

func (x *liquentSpotExchangeRPCStreamMarketsServer) Send(m *StreamMarketsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentSpotExchangeRPC_OrderbookV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderbookV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentSpotExchangeRPCServer).OrderbookV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/OrderbookV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentSpotExchangeRPCServer).OrderbookV2(ctx, req.(*OrderbookV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentSpotExchangeRPC_OrderbooksV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderbooksV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentSpotExchangeRPCServer).OrderbooksV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/OrderbooksV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentSpotExchangeRPCServer).OrderbooksV2(ctx, req.(*OrderbooksV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentSpotExchangeRPC_StreamOrderbookV2_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamOrderbookV2Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentSpotExchangeRPCServer).StreamOrderbookV2(m, &liquentSpotExchangeRPCStreamOrderbookV2Server{stream})
}

type LiquentSpotExchangeRPC_StreamOrderbookV2Server interface {
	Send(*StreamOrderbookV2Response) error
	grpc.ServerStream
}

type liquentSpotExchangeRPCStreamOrderbookV2Server struct {
	grpc.ServerStream
}

func (x *liquentSpotExchangeRPCStreamOrderbookV2Server) Send(m *StreamOrderbookV2Response) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentSpotExchangeRPC_StreamOrderbookUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamOrderbookUpdateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentSpotExchangeRPCServer).StreamOrderbookUpdate(m, &liquentSpotExchangeRPCStreamOrderbookUpdateServer{stream})
}

type LiquentSpotExchangeRPC_StreamOrderbookUpdateServer interface {
	Send(*StreamOrderbookUpdateResponse) error
	grpc.ServerStream
}

type liquentSpotExchangeRPCStreamOrderbookUpdateServer struct {
	grpc.ServerStream
}

func (x *liquentSpotExchangeRPCStreamOrderbookUpdateServer) Send(m *StreamOrderbookUpdateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentSpotExchangeRPC_Orders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentSpotExchangeRPCServer).Orders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/Orders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentSpotExchangeRPCServer).Orders(ctx, req.(*OrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentSpotExchangeRPC_StreamOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamOrdersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentSpotExchangeRPCServer).StreamOrders(m, &liquentSpotExchangeRPCStreamOrdersServer{stream})
}

type LiquentSpotExchangeRPC_StreamOrdersServer interface {
	Send(*StreamOrdersResponse) error
	grpc.ServerStream
}

type liquentSpotExchangeRPCStreamOrdersServer struct {
	grpc.ServerStream
}

func (x *liquentSpotExchangeRPCStreamOrdersServer) Send(m *StreamOrdersResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentSpotExchangeRPC_Trades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentSpotExchangeRPCServer).Trades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/Trades",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentSpotExchangeRPCServer).Trades(ctx, req.(*TradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentSpotExchangeRPC_StreamTrades_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTradesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentSpotExchangeRPCServer).StreamTrades(m, &liquentSpotExchangeRPCStreamTradesServer{stream})
}

type LiquentSpotExchangeRPC_StreamTradesServer interface {
	Send(*StreamTradesResponse) error
	grpc.ServerStream
}

type liquentSpotExchangeRPCStreamTradesServer struct {
	grpc.ServerStream
}

func (x *liquentSpotExchangeRPCStreamTradesServer) Send(m *StreamTradesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentSpotExchangeRPC_TradesV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradesV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentSpotExchangeRPCServer).TradesV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/TradesV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentSpotExchangeRPCServer).TradesV2(ctx, req.(*TradesV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentSpotExchangeRPC_StreamTradesV2_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTradesV2Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentSpotExchangeRPCServer).StreamTradesV2(m, &liquentSpotExchangeRPCStreamTradesV2Server{stream})
}

type LiquentSpotExchangeRPC_StreamTradesV2Server interface {
	Send(*StreamTradesV2Response) error
	grpc.ServerStream
}

type liquentSpotExchangeRPCStreamTradesV2Server struct {
	grpc.ServerStream
}

func (x *liquentSpotExchangeRPCStreamTradesV2Server) Send(m *StreamTradesV2Response) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentSpotExchangeRPC_SubaccountOrdersList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubaccountOrdersListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentSpotExchangeRPCServer).SubaccountOrdersList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/SubaccountOrdersList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentSpotExchangeRPCServer).SubaccountOrdersList(ctx, req.(*SubaccountOrdersListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentSpotExchangeRPC_SubaccountTradesList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubaccountTradesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentSpotExchangeRPCServer).SubaccountTradesList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/SubaccountTradesList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentSpotExchangeRPCServer).SubaccountTradesList(ctx, req.(*SubaccountTradesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentSpotExchangeRPC_OrdersHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrdersHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentSpotExchangeRPCServer).OrdersHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/OrdersHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentSpotExchangeRPCServer).OrdersHistory(ctx, req.(*OrdersHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentSpotExchangeRPC_StreamOrdersHistory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamOrdersHistoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentSpotExchangeRPCServer).StreamOrdersHistory(m, &liquentSpotExchangeRPCStreamOrdersHistoryServer{stream})
}

type LiquentSpotExchangeRPC_StreamOrdersHistoryServer interface {
	Send(*StreamOrdersHistoryResponse) error
	grpc.ServerStream
}

type liquentSpotExchangeRPCStreamOrdersHistoryServer struct {
	grpc.ServerStream
}

func (x *liquentSpotExchangeRPCStreamOrdersHistoryServer) Send(m *StreamOrdersHistoryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentSpotExchangeRPC_AtomicSwapHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AtomicSwapHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentSpotExchangeRPCServer).AtomicSwapHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_spot_exchange_rpc.LiquentSpotExchangeRPC/AtomicSwapHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentSpotExchangeRPCServer).AtomicSwapHistory(ctx, req.(*AtomicSwapHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LiquentSpotExchangeRPC_ServiceDesc is the grpc.ServiceDesc for LiquentSpotExchangeRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiquentSpotExchangeRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "liquent_spot_exchange_rpc.LiquentSpotExchangeRPC",
	HandlerType: (*LiquentSpotExchangeRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Markets",
			Handler:    _LiquentSpotExchangeRPC_Markets_Handler,
		},
		{
			MethodName: "Market",
			Handler:    _LiquentSpotExchangeRPC_Market_Handler,
		},
		{
			MethodName: "OrderbookV2",
			Handler:    _LiquentSpotExchangeRPC_OrderbookV2_Handler,
		},
		{
			MethodName: "OrderbooksV2",
			Handler:    _LiquentSpotExchangeRPC_OrderbooksV2_Handler,
		},
		{
			MethodName: "Orders",
			Handler:    _LiquentSpotExchangeRPC_Orders_Handler,
		},
		{
			MethodName: "Trades",
			Handler:    _LiquentSpotExchangeRPC_Trades_Handler,
		},
		{
			MethodName: "TradesV2",
			Handler:    _LiquentSpotExchangeRPC_TradesV2_Handler,
		},
		{
			MethodName: "SubaccountOrdersList",
			Handler:    _LiquentSpotExchangeRPC_SubaccountOrdersList_Handler,
		},
		{
			MethodName: "SubaccountTradesList",
			Handler:    _LiquentSpotExchangeRPC_SubaccountTradesList_Handler,
		},
		{
			MethodName: "OrdersHistory",
			Handler:    _LiquentSpotExchangeRPC_OrdersHistory_Handler,
		},
		{
			MethodName: "AtomicSwapHistory",
			Handler:    _LiquentSpotExchangeRPC_AtomicSwapHistory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMarkets",
			Handler:       _LiquentSpotExchangeRPC_StreamMarkets_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamOrderbookV2",
			Handler:       _LiquentSpotExchangeRPC_StreamOrderbookV2_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamOrderbookUpdate",
			Handler:       _LiquentSpotExchangeRPC_StreamOrderbookUpdate_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamOrders",
			Handler:       _LiquentSpotExchangeRPC_StreamOrders_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamTrades",
			Handler:       _LiquentSpotExchangeRPC_StreamTrades_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamTradesV2",
			Handler:       _LiquentSpotExchangeRPC_StreamTradesV2_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamOrdersHistory",
			Handler:       _LiquentSpotExchangeRPC_StreamOrdersHistory_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "goadesign_goagen_liquent_spot_exchange_rpc.proto",
}
