// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: goadesign_goagen_liquent_derivative_exchange_rpc.proto

package liquent_derivative_exchange_rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LiquentDerivativeExchangeRPCClient is the client API for LiquentDerivativeExchangeRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiquentDerivativeExchangeRPCClient interface {
	// Markets gets a list of Derivative Markets
	Markets(ctx context.Context, in *MarketsRequest, opts ...grpc.CallOption) (*MarketsResponse, error)
	// Market gets details of a single derivative market
	Market(ctx context.Context, in *MarketRequest, opts ...grpc.CallOption) (*MarketResponse, error)
	// StreamMarket streams live updates of selected derivative markets
	StreamMarket(ctx context.Context, in *StreamMarketRequest, opts ...grpc.CallOption) (LiquentDerivativeExchangeRPC_StreamMarketClient, error)
	// BinaryOptionsMarkets gets a list of Binary Options Markets
	BinaryOptionsMarkets(ctx context.Context, in *BinaryOptionsMarketsRequest, opts ...grpc.CallOption) (*BinaryOptionsMarketsResponse, error)
	// BinaryOptionMarket gets details of a single binary options market
	BinaryOptionsMarket(ctx context.Context, in *BinaryOptionsMarketRequest, opts ...grpc.CallOption) (*BinaryOptionsMarketResponse, error)
	// Orderbook gets the Orderbook of a Derivative Market
	OrderbookV2(ctx context.Context, in *OrderbookV2Request, opts ...grpc.CallOption) (*OrderbookV2Response, error)
	// Orderbooks gets the Orderbooks of requested derivative markets
	OrderbooksV2(ctx context.Context, in *OrderbooksV2Request, opts ...grpc.CallOption) (*OrderbooksV2Response, error)
	// Stream live snapshot updates of selected derivative market orderbook
	StreamOrderbookV2(ctx context.Context, in *StreamOrderbookV2Request, opts ...grpc.CallOption) (LiquentDerivativeExchangeRPC_StreamOrderbookV2Client, error)
	// Stream live level updates of selected derivative market orderbook
	StreamOrderbookUpdate(ctx context.Context, in *StreamOrderbookUpdateRequest, opts ...grpc.CallOption) (LiquentDerivativeExchangeRPC_StreamOrderbookUpdateClient, error)
	// DerivativeLimitOrders gets the limit orders of a derivative Market.
	Orders(ctx context.Context, in *OrdersRequest, opts ...grpc.CallOption) (*OrdersResponse, error)
	// Positions gets the positions for a trader.
	Positions(ctx context.Context, in *PositionsRequest, opts ...grpc.CallOption) (*PositionsResponse, error)
	// Positions gets the positions for a trader. V2 removed some redundant fields
	// and had performance improvements
	PositionsV2(ctx context.Context, in *PositionsV2Request, opts ...grpc.CallOption) (*PositionsV2Response, error)
	// LiquidablePositions gets all the liquidable positions.
	LiquidablePositions(ctx context.Context, in *LiquidablePositionsRequest, opts ...grpc.CallOption) (*LiquidablePositionsResponse, error)
	// FundingPayments gets the funding payments for a trader.
	FundingPayments(ctx context.Context, in *FundingPaymentsRequest, opts ...grpc.CallOption) (*FundingPaymentsResponse, error)
	// FundingRates gets the historical funding rates for a market.
	FundingRates(ctx context.Context, in *FundingRatesRequest, opts ...grpc.CallOption) (*FundingRatesResponse, error)
	// StreamPositions streams derivatives position updates. This is the legacy
	// version of the streamPositionsV2 endpoint. Use streamPositionsV2 instead.
	StreamPositions(ctx context.Context, in *StreamPositionsRequest, opts ...grpc.CallOption) (LiquentDerivativeExchangeRPC_StreamPositionsClient, error)
	// StreamPositionsV2 streams derivatives position updates.
	StreamPositionsV2(ctx context.Context, in *StreamPositionsV2Request, opts ...grpc.CallOption) (LiquentDerivativeExchangeRPC_StreamPositionsV2Client, error)
	// StreamOrders streams updates to individual orders of a Derivative Market.
	StreamOrders(ctx context.Context, in *StreamOrdersRequest, opts ...grpc.CallOption) (LiquentDerivativeExchangeRPC_StreamOrdersClient, error)
	// Trades gets the trades of a Derivative Market.
	Trades(ctx context.Context, in *TradesRequest, opts ...grpc.CallOption) (*TradesResponse, error)
	// Trades gets the trades of a Derivative Market.
	TradesV2(ctx context.Context, in *TradesV2Request, opts ...grpc.CallOption) (*TradesV2Response, error)
	// StreamTrades streams newly executed trades from Derivative Market.
	StreamTrades(ctx context.Context, in *StreamTradesRequest, opts ...grpc.CallOption) (LiquentDerivativeExchangeRPC_StreamTradesClient, error)
	// StreamTrades streams newly executed trades from Derivative Market.
	StreamTradesV2(ctx context.Context, in *StreamTradesV2Request, opts ...grpc.CallOption) (LiquentDerivativeExchangeRPC_StreamTradesV2Client, error)
	// SubaccountOrdersList lists orders posted from this subaccount.
	SubaccountOrdersList(ctx context.Context, in *SubaccountOrdersListRequest, opts ...grpc.CallOption) (*SubaccountOrdersListResponse, error)
	// SubaccountTradesList gets a list of derivatives trades executed by this
	// subaccount.
	SubaccountTradesList(ctx context.Context, in *SubaccountTradesListRequest, opts ...grpc.CallOption) (*SubaccountTradesListResponse, error)
	// Lists history orders posted from a subaccount
	OrdersHistory(ctx context.Context, in *OrdersHistoryRequest, opts ...grpc.CallOption) (*OrdersHistoryResponse, error)
	// Stream updates to historical orders of a derivative Market
	StreamOrdersHistory(ctx context.Context, in *StreamOrdersHistoryRequest, opts ...grpc.CallOption) (LiquentDerivativeExchangeRPC_StreamOrdersHistoryClient, error)
	// OpenInterest gets the open interest for a derivative market.
	OpenInterest(ctx context.Context, in *OpenInterestRequest, opts ...grpc.CallOption) (*OpenInterestResponse, error)
}

type liquentDerivativeExchangeRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewLiquentDerivativeExchangeRPCClient(cc grpc.ClientConnInterface) LiquentDerivativeExchangeRPCClient {
	return &liquentDerivativeExchangeRPCClient{cc}
}

func (c *liquentDerivativeExchangeRPCClient) Markets(ctx context.Context, in *MarketsRequest, opts ...grpc.CallOption) (*MarketsResponse, error) {
	out := new(MarketsResponse)
	err := c.cc.Invoke(ctx, "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/Markets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentDerivativeExchangeRPCClient) Market(ctx context.Context, in *MarketRequest, opts ...grpc.CallOption) (*MarketResponse, error) {
	out := new(MarketResponse)
	err := c.cc.Invoke(ctx, "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/Market", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentDerivativeExchangeRPCClient) StreamMarket(ctx context.Context, in *StreamMarketRequest, opts ...grpc.CallOption) (LiquentDerivativeExchangeRPC_StreamMarketClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentDerivativeExchangeRPC_ServiceDesc.Streams[0], "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/StreamMarket", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentDerivativeExchangeRPCStreamMarketClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentDerivativeExchangeRPC_StreamMarketClient interface {
	Recv() (*StreamMarketResponse, error)
	grpc.ClientStream
}

type liquentDerivativeExchangeRPCStreamMarketClient struct {
	grpc.ClientStream
}

func (x *liquentDerivativeExchangeRPCStreamMarketClient) Recv() (*StreamMarketResponse, error) {
	m := new(StreamMarketResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentDerivativeExchangeRPCClient) BinaryOptionsMarkets(ctx context.Context, in *BinaryOptionsMarketsRequest, opts ...grpc.CallOption) (*BinaryOptionsMarketsResponse, error) {
	out := new(BinaryOptionsMarketsResponse)
	err := c.cc.Invoke(ctx, "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/BinaryOptionsMarkets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentDerivativeExchangeRPCClient) BinaryOptionsMarket(ctx context.Context, in *BinaryOptionsMarketRequest, opts ...grpc.CallOption) (*BinaryOptionsMarketResponse, error) {
	out := new(BinaryOptionsMarketResponse)
	err := c.cc.Invoke(ctx, "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/BinaryOptionsMarket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentDerivativeExchangeRPCClient) OrderbookV2(ctx context.Context, in *OrderbookV2Request, opts ...grpc.CallOption) (*OrderbookV2Response, error) {
	out := new(OrderbookV2Response)
	err := c.cc.Invoke(ctx, "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/OrderbookV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentDerivativeExchangeRPCClient) OrderbooksV2(ctx context.Context, in *OrderbooksV2Request, opts ...grpc.CallOption) (*OrderbooksV2Response, error) {
	out := new(OrderbooksV2Response)
	err := c.cc.Invoke(ctx, "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/OrderbooksV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentDerivativeExchangeRPCClient) StreamOrderbookV2(ctx context.Context, in *StreamOrderbookV2Request, opts ...grpc.CallOption) (LiquentDerivativeExchangeRPC_StreamOrderbookV2Client, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentDerivativeExchangeRPC_ServiceDesc.Streams[1], "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/StreamOrderbookV2", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentDerivativeExchangeRPCStreamOrderbookV2Client{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentDerivativeExchangeRPC_StreamOrderbookV2Client interface {
	Recv() (*StreamOrderbookV2Response, error)
	grpc.ClientStream
}

type liquentDerivativeExchangeRPCStreamOrderbookV2Client struct {
	grpc.ClientStream
}

func (x *liquentDerivativeExchangeRPCStreamOrderbookV2Client) Recv() (*StreamOrderbookV2Response, error) {
	m := new(StreamOrderbookV2Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentDerivativeExchangeRPCClient) StreamOrderbookUpdate(ctx context.Context, in *StreamOrderbookUpdateRequest, opts ...grpc.CallOption) (LiquentDerivativeExchangeRPC_StreamOrderbookUpdateClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentDerivativeExchangeRPC_ServiceDesc.Streams[2], "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/StreamOrderbookUpdate", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentDerivativeExchangeRPCStreamOrderbookUpdateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentDerivativeExchangeRPC_StreamOrderbookUpdateClient interface {
	Recv() (*StreamOrderbookUpdateResponse, error)
	grpc.ClientStream
}

type liquentDerivativeExchangeRPCStreamOrderbookUpdateClient struct {
	grpc.ClientStream
}

func (x *liquentDerivativeExchangeRPCStreamOrderbookUpdateClient) Recv() (*StreamOrderbookUpdateResponse, error) {
	m := new(StreamOrderbookUpdateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentDerivativeExchangeRPCClient) Orders(ctx context.Context, in *OrdersRequest, opts ...grpc.CallOption) (*OrdersResponse, error) {
	out := new(OrdersResponse)
	err := c.cc.Invoke(ctx, "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/Orders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentDerivativeExchangeRPCClient) Positions(ctx context.Context, in *PositionsRequest, opts ...grpc.CallOption) (*PositionsResponse, error) {
	out := new(PositionsResponse)
	err := c.cc.Invoke(ctx, "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/Positions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentDerivativeExchangeRPCClient) PositionsV2(ctx context.Context, in *PositionsV2Request, opts ...grpc.CallOption) (*PositionsV2Response, error) {
	out := new(PositionsV2Response)
	err := c.cc.Invoke(ctx, "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/PositionsV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentDerivativeExchangeRPCClient) LiquidablePositions(ctx context.Context, in *LiquidablePositionsRequest, opts ...grpc.CallOption) (*LiquidablePositionsResponse, error) {
	out := new(LiquidablePositionsResponse)
	err := c.cc.Invoke(ctx, "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/LiquidablePositions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentDerivativeExchangeRPCClient) FundingPayments(ctx context.Context, in *FundingPaymentsRequest, opts ...grpc.CallOption) (*FundingPaymentsResponse, error) {
	out := new(FundingPaymentsResponse)
	err := c.cc.Invoke(ctx, "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/FundingPayments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentDerivativeExchangeRPCClient) FundingRates(ctx context.Context, in *FundingRatesRequest, opts ...grpc.CallOption) (*FundingRatesResponse, error) {
	out := new(FundingRatesResponse)
	err := c.cc.Invoke(ctx, "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/FundingRates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentDerivativeExchangeRPCClient) StreamPositions(ctx context.Context, in *StreamPositionsRequest, opts ...grpc.CallOption) (LiquentDerivativeExchangeRPC_StreamPositionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentDerivativeExchangeRPC_ServiceDesc.Streams[3], "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/StreamPositions", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentDerivativeExchangeRPCStreamPositionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentDerivativeExchangeRPC_StreamPositionsClient interface {
	Recv() (*StreamPositionsResponse, error)
	grpc.ClientStream
}

type liquentDerivativeExchangeRPCStreamPositionsClient struct {
	grpc.ClientStream
}

func (x *liquentDerivativeExchangeRPCStreamPositionsClient) Recv() (*StreamPositionsResponse, error) {
	m := new(StreamPositionsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentDerivativeExchangeRPCClient) StreamPositionsV2(ctx context.Context, in *StreamPositionsV2Request, opts ...grpc.CallOption) (LiquentDerivativeExchangeRPC_StreamPositionsV2Client, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentDerivativeExchangeRPC_ServiceDesc.Streams[4], "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/StreamPositionsV2", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentDerivativeExchangeRPCStreamPositionsV2Client{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentDerivativeExchangeRPC_StreamPositionsV2Client interface {
	Recv() (*StreamPositionsV2Response, error)
	grpc.ClientStream
}

type liquentDerivativeExchangeRPCStreamPositionsV2Client struct {
	grpc.ClientStream
}

func (x *liquentDerivativeExchangeRPCStreamPositionsV2Client) Recv() (*StreamPositionsV2Response, error) {
	m := new(StreamPositionsV2Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentDerivativeExchangeRPCClient) StreamOrders(ctx context.Context, in *StreamOrdersRequest, opts ...grpc.CallOption) (LiquentDerivativeExchangeRPC_StreamOrdersClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentDerivativeExchangeRPC_ServiceDesc.Streams[5], "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/StreamOrders", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentDerivativeExchangeRPCStreamOrdersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentDerivativeExchangeRPC_StreamOrdersClient interface {
	Recv() (*StreamOrdersResponse, error)
	grpc.ClientStream
}

type liquentDerivativeExchangeRPCStreamOrdersClient struct {
	grpc.ClientStream
}

func (x *liquentDerivativeExchangeRPCStreamOrdersClient) Recv() (*StreamOrdersResponse, error) {
	m := new(StreamOrdersResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentDerivativeExchangeRPCClient) Trades(ctx context.Context, in *TradesRequest, opts ...grpc.CallOption) (*TradesResponse, error) {
	out := new(TradesResponse)
	err := c.cc.Invoke(ctx, "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/Trades", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentDerivativeExchangeRPCClient) TradesV2(ctx context.Context, in *TradesV2Request, opts ...grpc.CallOption) (*TradesV2Response, error) {
	out := new(TradesV2Response)
	err := c.cc.Invoke(ctx, "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/TradesV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentDerivativeExchangeRPCClient) StreamTrades(ctx context.Context, in *StreamTradesRequest, opts ...grpc.CallOption) (LiquentDerivativeExchangeRPC_StreamTradesClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentDerivativeExchangeRPC_ServiceDesc.Streams[6], "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/StreamTrades", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentDerivativeExchangeRPCStreamTradesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentDerivativeExchangeRPC_StreamTradesClient interface {
	Recv() (*StreamTradesResponse, error)
	grpc.ClientStream
}

type liquentDerivativeExchangeRPCStreamTradesClient struct {
	grpc.ClientStream
}

func (x *liquentDerivativeExchangeRPCStreamTradesClient) Recv() (*StreamTradesResponse, error) {
	m := new(StreamTradesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentDerivativeExchangeRPCClient) StreamTradesV2(ctx context.Context, in *StreamTradesV2Request, opts ...grpc.CallOption) (LiquentDerivativeExchangeRPC_StreamTradesV2Client, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentDerivativeExchangeRPC_ServiceDesc.Streams[7], "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/StreamTradesV2", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentDerivativeExchangeRPCStreamTradesV2Client{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentDerivativeExchangeRPC_StreamTradesV2Client interface {
	Recv() (*StreamTradesV2Response, error)
	grpc.ClientStream
}

type liquentDerivativeExchangeRPCStreamTradesV2Client struct {
	grpc.ClientStream
}

func (x *liquentDerivativeExchangeRPCStreamTradesV2Client) Recv() (*StreamTradesV2Response, error) {
	m := new(StreamTradesV2Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentDerivativeExchangeRPCClient) SubaccountOrdersList(ctx context.Context, in *SubaccountOrdersListRequest, opts ...grpc.CallOption) (*SubaccountOrdersListResponse, error) {
	out := new(SubaccountOrdersListResponse)
	err := c.cc.Invoke(ctx, "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/SubaccountOrdersList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentDerivativeExchangeRPCClient) SubaccountTradesList(ctx context.Context, in *SubaccountTradesListRequest, opts ...grpc.CallOption) (*SubaccountTradesListResponse, error) {
	out := new(SubaccountTradesListResponse)
	err := c.cc.Invoke(ctx, "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/SubaccountTradesList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentDerivativeExchangeRPCClient) OrdersHistory(ctx context.Context, in *OrdersHistoryRequest, opts ...grpc.CallOption) (*OrdersHistoryResponse, error) {
	out := new(OrdersHistoryResponse)
	err := c.cc.Invoke(ctx, "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/OrdersHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentDerivativeExchangeRPCClient) StreamOrdersHistory(ctx context.Context, in *StreamOrdersHistoryRequest, opts ...grpc.CallOption) (LiquentDerivativeExchangeRPC_StreamOrdersHistoryClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentDerivativeExchangeRPC_ServiceDesc.Streams[8], "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/StreamOrdersHistory", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentDerivativeExchangeRPCStreamOrdersHistoryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentDerivativeExchangeRPC_StreamOrdersHistoryClient interface {
	Recv() (*StreamOrdersHistoryResponse, error)
	grpc.ClientStream
}

type liquentDerivativeExchangeRPCStreamOrdersHistoryClient struct {
	grpc.ClientStream
}

func (x *liquentDerivativeExchangeRPCStreamOrdersHistoryClient) Recv() (*StreamOrdersHistoryResponse, error) {
	m := new(StreamOrdersHistoryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentDerivativeExchangeRPCClient) OpenInterest(ctx context.Context, in *OpenInterestRequest, opts ...grpc.CallOption) (*OpenInterestResponse, error) {
	out := new(OpenInterestResponse)
	err := c.cc.Invoke(ctx, "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/OpenInterest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiquentDerivativeExchangeRPCServer is the server API for LiquentDerivativeExchangeRPC service.
// All implementations must embed UnimplementedLiquentDerivativeExchangeRPCServer
// for forward compatibility
type LiquentDerivativeExchangeRPCServer interface {
	// Markets gets a list of Derivative Markets
	Markets(context.Context, *MarketsRequest) (*MarketsResponse, error)
	// Market gets details of a single derivative market
	Market(context.Context, *MarketRequest) (*MarketResponse, error)
	// StreamMarket streams live updates of selected derivative markets
	StreamMarket(*StreamMarketRequest, LiquentDerivativeExchangeRPC_StreamMarketServer) error
	// BinaryOptionsMarkets gets a list of Binary Options Markets
	BinaryOptionsMarkets(context.Context, *BinaryOptionsMarketsRequest) (*BinaryOptionsMarketsResponse, error)
	// BinaryOptionMarket gets details of a single binary options market
	BinaryOptionsMarket(context.Context, *BinaryOptionsMarketRequest) (*BinaryOptionsMarketResponse, error)
	// Orderbook gets the Orderbook of a Derivative Market
	OrderbookV2(context.Context, *OrderbookV2Request) (*OrderbookV2Response, error)
	// Orderbooks gets the Orderbooks of requested derivative markets
	OrderbooksV2(context.Context, *OrderbooksV2Request) (*OrderbooksV2Response, error)
	// Stream live snapshot updates of selected derivative market orderbook
	StreamOrderbookV2(*StreamOrderbookV2Request, LiquentDerivativeExchangeRPC_StreamOrderbookV2Server) error
	// Stream live level updates of selected derivative market orderbook
	StreamOrderbookUpdate(*StreamOrderbookUpdateRequest, LiquentDerivativeExchangeRPC_StreamOrderbookUpdateServer) error
	// DerivativeLimitOrders gets the limit orders of a derivative Market.
	Orders(context.Context, *OrdersRequest) (*OrdersResponse, error)
	// Positions gets the positions for a trader.
	Positions(context.Context, *PositionsRequest) (*PositionsResponse, error)
	// Positions gets the positions for a trader. V2 removed some redundant fields
	// and had performance improvements
	PositionsV2(context.Context, *PositionsV2Request) (*PositionsV2Response, error)
	// LiquidablePositions gets all the liquidable positions.
	LiquidablePositions(context.Context, *LiquidablePositionsRequest) (*LiquidablePositionsResponse, error)
	// FundingPayments gets the funding payments for a trader.
	FundingPayments(context.Context, *FundingPaymentsRequest) (*FundingPaymentsResponse, error)
	// FundingRates gets the historical funding rates for a market.
	FundingRates(context.Context, *FundingRatesRequest) (*FundingRatesResponse, error)
	// StreamPositions streams derivatives position updates. This is the legacy
	// version of the streamPositionsV2 endpoint. Use streamPositionsV2 instead.
	StreamPositions(*StreamPositionsRequest, LiquentDerivativeExchangeRPC_StreamPositionsServer) error
	// StreamPositionsV2 streams derivatives position updates.
	StreamPositionsV2(*StreamPositionsV2Request, LiquentDerivativeExchangeRPC_StreamPositionsV2Server) error
	// StreamOrders streams updates to individual orders of a Derivative Market.
	StreamOrders(*StreamOrdersRequest, LiquentDerivativeExchangeRPC_StreamOrdersServer) error
	// Trades gets the trades of a Derivative Market.
	Trades(context.Context, *TradesRequest) (*TradesResponse, error)
	// Trades gets the trades of a Derivative Market.
	TradesV2(context.Context, *TradesV2Request) (*TradesV2Response, error)
	// StreamTrades streams newly executed trades from Derivative Market.
	StreamTrades(*StreamTradesRequest, LiquentDerivativeExchangeRPC_StreamTradesServer) error
	// StreamTrades streams newly executed trades from Derivative Market.
	StreamTradesV2(*StreamTradesV2Request, LiquentDerivativeExchangeRPC_StreamTradesV2Server) error
	// SubaccountOrdersList lists orders posted from this subaccount.
	SubaccountOrdersList(context.Context, *SubaccountOrdersListRequest) (*SubaccountOrdersListResponse, error)
	// SubaccountTradesList gets a list of derivatives trades executed by this
	// subaccount.
	SubaccountTradesList(context.Context, *SubaccountTradesListRequest) (*SubaccountTradesListResponse, error)
	// Lists history orders posted from a subaccount
	OrdersHistory(context.Context, *OrdersHistoryRequest) (*OrdersHistoryResponse, error)
	// Stream updates to historical orders of a derivative Market
	StreamOrdersHistory(*StreamOrdersHistoryRequest, LiquentDerivativeExchangeRPC_StreamOrdersHistoryServer) error
	// OpenInterest gets the open interest for a derivative market.
	OpenInterest(context.Context, *OpenInterestRequest) (*OpenInterestResponse, error)
	mustEmbedUnimplementedLiquentDerivativeExchangeRPCServer()
}

// UnimplementedLiquentDerivativeExchangeRPCServer must be embedded to have forward compatible implementations.
type UnimplementedLiquentDerivativeExchangeRPCServer struct {
}

func (UnimplementedLiquentDerivativeExchangeRPCServer) Markets(context.Context, *MarketsRequest) (*MarketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Markets not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) Market(context.Context, *MarketRequest) (*MarketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Market not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) StreamMarket(*StreamMarketRequest, LiquentDerivativeExchangeRPC_StreamMarketServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMarket not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) BinaryOptionsMarkets(context.Context, *BinaryOptionsMarketsRequest) (*BinaryOptionsMarketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BinaryOptionsMarkets not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) BinaryOptionsMarket(context.Context, *BinaryOptionsMarketRequest) (*BinaryOptionsMarketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BinaryOptionsMarket not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) OrderbookV2(context.Context, *OrderbookV2Request) (*OrderbookV2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderbookV2 not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) OrderbooksV2(context.Context, *OrderbooksV2Request) (*OrderbooksV2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderbooksV2 not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) StreamOrderbookV2(*StreamOrderbookV2Request, LiquentDerivativeExchangeRPC_StreamOrderbookV2Server) error {
	return status.Errorf(codes.Unimplemented, "method StreamOrderbookV2 not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) StreamOrderbookUpdate(*StreamOrderbookUpdateRequest, LiquentDerivativeExchangeRPC_StreamOrderbookUpdateServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamOrderbookUpdate not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) Orders(context.Context, *OrdersRequest) (*OrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Orders not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) Positions(context.Context, *PositionsRequest) (*PositionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Positions not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) PositionsV2(context.Context, *PositionsV2Request) (*PositionsV2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PositionsV2 not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) LiquidablePositions(context.Context, *LiquidablePositionsRequest) (*LiquidablePositionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LiquidablePositions not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) FundingPayments(context.Context, *FundingPaymentsRequest) (*FundingPaymentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FundingPayments not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) FundingRates(context.Context, *FundingRatesRequest) (*FundingRatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FundingRates not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) StreamPositions(*StreamPositionsRequest, LiquentDerivativeExchangeRPC_StreamPositionsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPositions not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) StreamPositionsV2(*StreamPositionsV2Request, LiquentDerivativeExchangeRPC_StreamPositionsV2Server) error {
	return status.Errorf(codes.Unimplemented, "method StreamPositionsV2 not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) StreamOrders(*StreamOrdersRequest, LiquentDerivativeExchangeRPC_StreamOrdersServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamOrders not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) Trades(context.Context, *TradesRequest) (*TradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Trades not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) TradesV2(context.Context, *TradesV2Request) (*TradesV2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TradesV2 not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) StreamTrades(*StreamTradesRequest, LiquentDerivativeExchangeRPC_StreamTradesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamTrades not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) StreamTradesV2(*StreamTradesV2Request, LiquentDerivativeExchangeRPC_StreamTradesV2Server) error {
	return status.Errorf(codes.Unimplemented, "method StreamTradesV2 not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) SubaccountOrdersList(context.Context, *SubaccountOrdersListRequest) (*SubaccountOrdersListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubaccountOrdersList not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) SubaccountTradesList(context.Context, *SubaccountTradesListRequest) (*SubaccountTradesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubaccountTradesList not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) OrdersHistory(context.Context, *OrdersHistoryRequest) (*OrdersHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrdersHistory not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) StreamOrdersHistory(*StreamOrdersHistoryRequest, LiquentDerivativeExchangeRPC_StreamOrdersHistoryServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamOrdersHistory not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) OpenInterest(context.Context, *OpenInterestRequest) (*OpenInterestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenInterest not implemented")
}
func (UnimplementedLiquentDerivativeExchangeRPCServer) mustEmbedUnimplementedLiquentDerivativeExchangeRPCServer() {
}

// UnsafeLiquentDerivativeExchangeRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiquentDerivativeExchangeRPCServer will
// result in compilation errors.
type UnsafeLiquentDerivativeExchangeRPCServer interface {
	mustEmbedUnimplementedLiquentDerivativeExchangeRPCServer()
}

func RegisterLiquentDerivativeExchangeRPCServer(s grpc.ServiceRegistrar, srv LiquentDerivativeExchangeRPCServer) {
	s.RegisterService(&LiquentDerivativeExchangeRPC_ServiceDesc, srv)
}

func _LiquentDerivativeExchangeRPC_Markets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentDerivativeExchangeRPCServer).Markets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/Markets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentDerivativeExchangeRPCServer).Markets(ctx, req.(*MarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentDerivativeExchangeRPC_Market_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentDerivativeExchangeRPCServer).Market(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/Market",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentDerivativeExchangeRPCServer).Market(ctx, req.(*MarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentDerivativeExchangeRPC_StreamMarket_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMarketRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentDerivativeExchangeRPCServer).StreamMarket(m, &liquentDerivativeExchangeRPCStreamMarketServer{stream})
}

type LiquentDerivativeExchangeRPC_StreamMarketServer interface {
	Send(*StreamMarketResponse) error
	grpc.ServerStream
}

type liquentDerivativeExchangeRPCStreamMarketServer struct {
	grpc.ServerStream
}

func (x *liquentDerivativeExchangeRPCStreamMarketServer) Send(m *StreamMarketResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentDerivativeExchangeRPC_BinaryOptionsMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinaryOptionsMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentDerivativeExchangeRPCServer).BinaryOptionsMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/BinaryOptionsMarkets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentDerivativeExchangeRPCServer).BinaryOptionsMarkets(ctx, req.(*BinaryOptionsMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentDerivativeExchangeRPC_BinaryOptionsMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinaryOptionsMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentDerivativeExchangeRPCServer).BinaryOptionsMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/BinaryOptionsMarket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentDerivativeExchangeRPCServer).BinaryOptionsMarket(ctx, req.(*BinaryOptionsMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentDerivativeExchangeRPC_OrderbookV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderbookV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentDerivativeExchangeRPCServer).OrderbookV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/OrderbookV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentDerivativeExchangeRPCServer).OrderbookV2(ctx, req.(*OrderbookV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentDerivativeExchangeRPC_OrderbooksV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderbooksV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentDerivativeExchangeRPCServer).OrderbooksV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/OrderbooksV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentDerivativeExchangeRPCServer).OrderbooksV2(ctx, req.(*OrderbooksV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentDerivativeExchangeRPC_StreamOrderbookV2_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamOrderbookV2Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentDerivativeExchangeRPCServer).StreamOrderbookV2(m, &liquentDerivativeExchangeRPCStreamOrderbookV2Server{stream})
}

type LiquentDerivativeExchangeRPC_StreamOrderbookV2Server interface {
	Send(*StreamOrderbookV2Response) error
	grpc.ServerStream
}

type liquentDerivativeExchangeRPCStreamOrderbookV2Server struct {
	grpc.ServerStream
}

func (x *liquentDerivativeExchangeRPCStreamOrderbookV2Server) Send(m *StreamOrderbookV2Response) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentDerivativeExchangeRPC_StreamOrderbookUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamOrderbookUpdateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentDerivativeExchangeRPCServer).StreamOrderbookUpdate(m, &liquentDerivativeExchangeRPCStreamOrderbookUpdateServer{stream})
}

type LiquentDerivativeExchangeRPC_StreamOrderbookUpdateServer interface {
	Send(*StreamOrderbookUpdateResponse) error
	grpc.ServerStream
}

type liquentDerivativeExchangeRPCStreamOrderbookUpdateServer struct {
	grpc.ServerStream
}

func (x *liquentDerivativeExchangeRPCStreamOrderbookUpdateServer) Send(m *StreamOrderbookUpdateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentDerivativeExchangeRPC_Orders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentDerivativeExchangeRPCServer).Orders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/Orders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentDerivativeExchangeRPCServer).Orders(ctx, req.(*OrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentDerivativeExchangeRPC_Positions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentDerivativeExchangeRPCServer).Positions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/Positions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentDerivativeExchangeRPCServer).Positions(ctx, req.(*PositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentDerivativeExchangeRPC_PositionsV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionsV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentDerivativeExchangeRPCServer).PositionsV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/PositionsV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentDerivativeExchangeRPCServer).PositionsV2(ctx, req.(*PositionsV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentDerivativeExchangeRPC_LiquidablePositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LiquidablePositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentDerivativeExchangeRPCServer).LiquidablePositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/LiquidablePositions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentDerivativeExchangeRPCServer).LiquidablePositions(ctx, req.(*LiquidablePositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentDerivativeExchangeRPC_FundingPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FundingPaymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentDerivativeExchangeRPCServer).FundingPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/FundingPayments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentDerivativeExchangeRPCServer).FundingPayments(ctx, req.(*FundingPaymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentDerivativeExchangeRPC_FundingRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FundingRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentDerivativeExchangeRPCServer).FundingRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/FundingRates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentDerivativeExchangeRPCServer).FundingRates(ctx, req.(*FundingRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentDerivativeExchangeRPC_StreamPositions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPositionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentDerivativeExchangeRPCServer).StreamPositions(m, &liquentDerivativeExchangeRPCStreamPositionsServer{stream})
}

type LiquentDerivativeExchangeRPC_StreamPositionsServer interface {
	Send(*StreamPositionsResponse) error
	grpc.ServerStream
}

type liquentDerivativeExchangeRPCStreamPositionsServer struct {
	grpc.ServerStream
}

func (x *liquentDerivativeExchangeRPCStreamPositionsServer) Send(m *StreamPositionsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentDerivativeExchangeRPC_StreamPositionsV2_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPositionsV2Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentDerivativeExchangeRPCServer).StreamPositionsV2(m, &liquentDerivativeExchangeRPCStreamPositionsV2Server{stream})
}

type LiquentDerivativeExchangeRPC_StreamPositionsV2Server interface {
	Send(*StreamPositionsV2Response) error
	grpc.ServerStream
}

type liquentDerivativeExchangeRPCStreamPositionsV2Server struct {
	grpc.ServerStream
}

func (x *liquentDerivativeExchangeRPCStreamPositionsV2Server) Send(m *StreamPositionsV2Response) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentDerivativeExchangeRPC_StreamOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamOrdersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentDerivativeExchangeRPCServer).StreamOrders(m, &liquentDerivativeExchangeRPCStreamOrdersServer{stream})
}

type LiquentDerivativeExchangeRPC_StreamOrdersServer interface {
	Send(*StreamOrdersResponse) error
	grpc.ServerStream
}

type liquentDerivativeExchangeRPCStreamOrdersServer struct {
	grpc.ServerStream
}

func (x *liquentDerivativeExchangeRPCStreamOrdersServer) Send(m *StreamOrdersResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentDerivativeExchangeRPC_Trades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentDerivativeExchangeRPCServer).Trades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/Trades",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentDerivativeExchangeRPCServer).Trades(ctx, req.(*TradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentDerivativeExchangeRPC_TradesV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradesV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentDerivativeExchangeRPCServer).TradesV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/TradesV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentDerivativeExchangeRPCServer).TradesV2(ctx, req.(*TradesV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentDerivativeExchangeRPC_StreamTrades_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTradesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentDerivativeExchangeRPCServer).StreamTrades(m, &liquentDerivativeExchangeRPCStreamTradesServer{stream})
}

type LiquentDerivativeExchangeRPC_StreamTradesServer interface {
	Send(*StreamTradesResponse) error
	grpc.ServerStream
}

type liquentDerivativeExchangeRPCStreamTradesServer struct {
	grpc.ServerStream
}

func (x *liquentDerivativeExchangeRPCStreamTradesServer) Send(m *StreamTradesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentDerivativeExchangeRPC_StreamTradesV2_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTradesV2Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentDerivativeExchangeRPCServer).StreamTradesV2(m, &liquentDerivativeExchangeRPCStreamTradesV2Server{stream})
}

type LiquentDerivativeExchangeRPC_StreamTradesV2Server interface {
	Send(*StreamTradesV2Response) error
	grpc.ServerStream
}

type liquentDerivativeExchangeRPCStreamTradesV2Server struct {
	grpc.ServerStream
}

func (x *liquentDerivativeExchangeRPCStreamTradesV2Server) Send(m *StreamTradesV2Response) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentDerivativeExchangeRPC_SubaccountOrdersList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubaccountOrdersListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentDerivativeExchangeRPCServer).SubaccountOrdersList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/SubaccountOrdersList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentDerivativeExchangeRPCServer).SubaccountOrdersList(ctx, req.(*SubaccountOrdersListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentDerivativeExchangeRPC_SubaccountTradesList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubaccountTradesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentDerivativeExchangeRPCServer).SubaccountTradesList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/SubaccountTradesList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentDerivativeExchangeRPCServer).SubaccountTradesList(ctx, req.(*SubaccountTradesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentDerivativeExchangeRPC_OrdersHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrdersHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentDerivativeExchangeRPCServer).OrdersHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/OrdersHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentDerivativeExchangeRPCServer).OrdersHistory(ctx, req.(*OrdersHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentDerivativeExchangeRPC_StreamOrdersHistory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamOrdersHistoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentDerivativeExchangeRPCServer).StreamOrdersHistory(m, &liquentDerivativeExchangeRPCStreamOrdersHistoryServer{stream})
}

type LiquentDerivativeExchangeRPC_StreamOrdersHistoryServer interface {
	Send(*StreamOrdersHistoryResponse) error
	grpc.ServerStream
}

type liquentDerivativeExchangeRPCStreamOrdersHistoryServer struct {
	grpc.ServerStream
}

func (x *liquentDerivativeExchangeRPCStreamOrdersHistoryServer) Send(m *StreamOrdersHistoryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentDerivativeExchangeRPC_OpenInterest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenInterestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentDerivativeExchangeRPCServer).OpenInterest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC/OpenInterest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentDerivativeExchangeRPCServer).OpenInterest(ctx, req.(*OpenInterestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LiquentDerivativeExchangeRPC_ServiceDesc is the grpc.ServiceDesc for LiquentDerivativeExchangeRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiquentDerivativeExchangeRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "liquent_derivative_exchange_rpc.LiquentDerivativeExchangeRPC",
	HandlerType: (*LiquentDerivativeExchangeRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Markets",
			Handler:    _LiquentDerivativeExchangeRPC_Markets_Handler,
		},
		{
			MethodName: "Market",
			Handler:    _LiquentDerivativeExchangeRPC_Market_Handler,
		},
		{
			MethodName: "BinaryOptionsMarkets",
			Handler:    _LiquentDerivativeExchangeRPC_BinaryOptionsMarkets_Handler,
		},
		{
			MethodName: "BinaryOptionsMarket",
			Handler:    _LiquentDerivativeExchangeRPC_BinaryOptionsMarket_Handler,
		},
		{
			MethodName: "OrderbookV2",
			Handler:    _LiquentDerivativeExchangeRPC_OrderbookV2_Handler,
		},
		{
			MethodName: "OrderbooksV2",
			Handler:    _LiquentDerivativeExchangeRPC_OrderbooksV2_Handler,
		},
		{
			MethodName: "Orders",
			Handler:    _LiquentDerivativeExchangeRPC_Orders_Handler,
		},
		{
			MethodName: "Positions",
			Handler:    _LiquentDerivativeExchangeRPC_Positions_Handler,
		},
		{
			MethodName: "PositionsV2",
			Handler:    _LiquentDerivativeExchangeRPC_PositionsV2_Handler,
		},
		{
			MethodName: "LiquidablePositions",
			Handler:    _LiquentDerivativeExchangeRPC_LiquidablePositions_Handler,
		},
		{
			MethodName: "FundingPayments",
			Handler:    _LiquentDerivativeExchangeRPC_FundingPayments_Handler,
		},
		{
			MethodName: "FundingRates",
			Handler:    _LiquentDerivativeExchangeRPC_FundingRates_Handler,
		},
		{
			MethodName: "Trades",
			Handler:    _LiquentDerivativeExchangeRPC_Trades_Handler,
		},
		{
			MethodName: "TradesV2",
			Handler:    _LiquentDerivativeExchangeRPC_TradesV2_Handler,
		},
		{
			MethodName: "SubaccountOrdersList",
			Handler:    _LiquentDerivativeExchangeRPC_SubaccountOrdersList_Handler,
		},
		{
			MethodName: "SubaccountTradesList",
			Handler:    _LiquentDerivativeExchangeRPC_SubaccountTradesList_Handler,
		},
		{
			MethodName: "OrdersHistory",
			Handler:    _LiquentDerivativeExchangeRPC_OrdersHistory_Handler,
		},
		{
			MethodName: "OpenInterest",
			Handler:    _LiquentDerivativeExchangeRPC_OpenInterest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMarket",
			Handler:       _LiquentDerivativeExchangeRPC_StreamMarket_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamOrderbookV2",
			Handler:       _LiquentDerivativeExchangeRPC_StreamOrderbookV2_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamOrderbookUpdate",
			Handler:       _LiquentDerivativeExchangeRPC_StreamOrderbookUpdate_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamPositions",
			Handler:       _LiquentDerivativeExchangeRPC_StreamPositions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamPositionsV2",
			Handler:       _LiquentDerivativeExchangeRPC_StreamPositionsV2_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamOrders",
			Handler:       _LiquentDerivativeExchangeRPC_StreamOrders_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamTrades",
			Handler:       _LiquentDerivativeExchangeRPC_StreamTrades_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamTradesV2",
			Handler:       _LiquentDerivativeExchangeRPC_StreamTradesV2_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamOrdersHistory",
			Handler:       _LiquentDerivativeExchangeRPC_StreamOrdersHistory_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "goadesign_goagen_liquent_derivative_exchange_rpc.proto",
}
