// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: goadesign_goagen_liquent_insurance_rpc.proto

package liquent_insurance_rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LiquentInsuranceRPCClient is the client API for LiquentInsuranceRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiquentInsuranceRPCClient interface {
	// Funds lists all insurance funds.
	Funds(ctx context.Context, in *FundsRequest, opts ...grpc.CallOption) (*FundsResponse, error)
	// Funds returns an insurance fund for a given insurance fund token denom.
	Fund(ctx context.Context, in *FundRequest, opts ...grpc.CallOption) (*FundResponse, error)
	// PendingRedemptions lists all pending redemptions according to a filter
	Redemptions(ctx context.Context, in *RedemptionsRequest, opts ...grpc.CallOption) (*RedemptionsResponse, error)
}

type liquentInsuranceRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewLiquentInsuranceRPCClient(cc grpc.ClientConnInterface) LiquentInsuranceRPCClient {
	return &liquentInsuranceRPCClient{cc}
}

func (c *liquentInsuranceRPCClient) Funds(ctx context.Context, in *FundsRequest, opts ...grpc.CallOption) (*FundsResponse, error) {
	out := new(FundsResponse)
	err := c.cc.Invoke(ctx, "/liquent_insurance_rpc.LiquentInsuranceRPC/Funds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentInsuranceRPCClient) Fund(ctx context.Context, in *FundRequest, opts ...grpc.CallOption) (*FundResponse, error) {
	out := new(FundResponse)
	err := c.cc.Invoke(ctx, "/liquent_insurance_rpc.LiquentInsuranceRPC/Fund", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentInsuranceRPCClient) Redemptions(ctx context.Context, in *RedemptionsRequest, opts ...grpc.CallOption) (*RedemptionsResponse, error) {
	out := new(RedemptionsResponse)
	err := c.cc.Invoke(ctx, "/liquent_insurance_rpc.LiquentInsuranceRPC/Redemptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiquentInsuranceRPCServer is the server API for LiquentInsuranceRPC service.
// All implementations must embed UnimplementedLiquentInsuranceRPCServer
// for forward compatibility
type LiquentInsuranceRPCServer interface {
	// Funds lists all insurance funds.
	Funds(context.Context, *FundsRequest) (*FundsResponse, error)
	// Funds returns an insurance fund for a given insurance fund token denom.
	Fund(context.Context, *FundRequest) (*FundResponse, error)
	// PendingRedemptions lists all pending redemptions according to a filter
	Redemptions(context.Context, *RedemptionsRequest) (*RedemptionsResponse, error)
	mustEmbedUnimplementedLiquentInsuranceRPCServer()
}

// UnimplementedLiquentInsuranceRPCServer must be embedded to have forward compatible implementations.
type UnimplementedLiquentInsuranceRPCServer struct {
}

func (UnimplementedLiquentInsuranceRPCServer) Funds(context.Context, *FundsRequest) (*FundsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Funds not implemented")
}
func (UnimplementedLiquentInsuranceRPCServer) Fund(context.Context, *FundRequest) (*FundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fund not implemented")
}
func (UnimplementedLiquentInsuranceRPCServer) Redemptions(context.Context, *RedemptionsRequest) (*RedemptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Redemptions not implemented")
}
func (UnimplementedLiquentInsuranceRPCServer) mustEmbedUnimplementedLiquentInsuranceRPCServer() {}

// UnsafeLiquentInsuranceRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiquentInsuranceRPCServer will
// result in compilation errors.
type UnsafeLiquentInsuranceRPCServer interface {
	mustEmbedUnimplementedLiquentInsuranceRPCServer()
}

func RegisterLiquentInsuranceRPCServer(s grpc.ServiceRegistrar, srv LiquentInsuranceRPCServer) {
	s.RegisterService(&LiquentInsuranceRPC_ServiceDesc, srv)
}

func _LiquentInsuranceRPC_Funds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentInsuranceRPCServer).Funds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_insurance_rpc.LiquentInsuranceRPC/Funds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentInsuranceRPCServer).Funds(ctx, req.(*FundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentInsuranceRPC_Fund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentInsuranceRPCServer).Fund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_insurance_rpc.LiquentInsuranceRPC/Fund",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentInsuranceRPCServer).Fund(ctx, req.(*FundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentInsuranceRPC_Redemptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedemptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentInsuranceRPCServer).Redemptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_insurance_rpc.LiquentInsuranceRPC/Redemptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentInsuranceRPCServer).Redemptions(ctx, req.(*RedemptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LiquentInsuranceRPC_ServiceDesc is the grpc.ServiceDesc for LiquentInsuranceRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiquentInsuranceRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "liquent_insurance_rpc.LiquentInsuranceRPC",
	HandlerType: (*LiquentInsuranceRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Funds",
			Handler:    _LiquentInsuranceRPC_Funds_Handler,
		},
		{
			MethodName: "Fund",
			Handler:    _LiquentInsuranceRPC_Fund_Handler,
		},
		{
			MethodName: "Redemptions",
			Handler:    _LiquentInsuranceRPC_Redemptions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goadesign_goagen_liquent_insurance_rpc.proto",
}
