// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: goadesign_goagen_liquent_auction_rpc.proto

package liquent_auction_rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LiquentAuctionRPCClient is the client API for LiquentAuctionRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiquentAuctionRPCClient interface {
	// Provide historical auction info for a given auction
	AuctionEndpoint(ctx context.Context, in *AuctionEndpointRequest, opts ...grpc.CallOption) (*AuctionEndpointResponse, error)
	// Provide the historical auctions info
	Auctions(ctx context.Context, in *AuctionsRequest, opts ...grpc.CallOption) (*AuctionsResponse, error)
	// StreamBids streams new bids of an auction.
	StreamBids(ctx context.Context, in *StreamBidsRequest, opts ...grpc.CallOption) (LiquentAuctionRPC_StreamBidsClient, error)
	// LqtBurntEndpoint returns the total amount of LQT burnt in auctions.
	LqtBurntEndpoint(ctx context.Context, in *LqtBurntEndpointRequest, opts ...grpc.CallOption) (*LqtBurntEndpointResponse, error)
}

type liquentAuctionRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewLiquentAuctionRPCClient(cc grpc.ClientConnInterface) LiquentAuctionRPCClient {
	return &liquentAuctionRPCClient{cc}
}

func (c *liquentAuctionRPCClient) AuctionEndpoint(ctx context.Context, in *AuctionEndpointRequest, opts ...grpc.CallOption) (*AuctionEndpointResponse, error) {
	out := new(AuctionEndpointResponse)
	err := c.cc.Invoke(ctx, "/liquent_auction_rpc.LiquentAuctionRPC/AuctionEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentAuctionRPCClient) Auctions(ctx context.Context, in *AuctionsRequest, opts ...grpc.CallOption) (*AuctionsResponse, error) {
	out := new(AuctionsResponse)
	err := c.cc.Invoke(ctx, "/liquent_auction_rpc.LiquentAuctionRPC/Auctions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentAuctionRPCClient) StreamBids(ctx context.Context, in *StreamBidsRequest, opts ...grpc.CallOption) (LiquentAuctionRPC_StreamBidsClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentAuctionRPC_ServiceDesc.Streams[0], "/liquent_auction_rpc.LiquentAuctionRPC/StreamBids", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentAuctionRPCStreamBidsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentAuctionRPC_StreamBidsClient interface {
	Recv() (*StreamBidsResponse, error)
	grpc.ClientStream
}

type liquentAuctionRPCStreamBidsClient struct {
	grpc.ClientStream
}

func (x *liquentAuctionRPCStreamBidsClient) Recv() (*StreamBidsResponse, error) {
	m := new(StreamBidsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentAuctionRPCClient) LqtBurntEndpoint(ctx context.Context, in *LqtBurntEndpointRequest, opts ...grpc.CallOption) (*LqtBurntEndpointResponse, error) {
	out := new(LqtBurntEndpointResponse)
	err := c.cc.Invoke(ctx, "/liquent_auction_rpc.LiquentAuctionRPC/LqtBurntEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiquentAuctionRPCServer is the server API for LiquentAuctionRPC service.
// All implementations must embed UnimplementedLiquentAuctionRPCServer
// for forward compatibility
type LiquentAuctionRPCServer interface {
	// Provide historical auction info for a given auction
	AuctionEndpoint(context.Context, *AuctionEndpointRequest) (*AuctionEndpointResponse, error)
	// Provide the historical auctions info
	Auctions(context.Context, *AuctionsRequest) (*AuctionsResponse, error)
	// StreamBids streams new bids of an auction.
	StreamBids(*StreamBidsRequest, LiquentAuctionRPC_StreamBidsServer) error
	// LqtBurntEndpoint returns the total amount of LQT burnt in auctions.
	LqtBurntEndpoint(context.Context, *LqtBurntEndpointRequest) (*LqtBurntEndpointResponse, error)
	mustEmbedUnimplementedLiquentAuctionRPCServer()
}

// UnimplementedLiquentAuctionRPCServer must be embedded to have forward compatible implementations.
type UnimplementedLiquentAuctionRPCServer struct {
}

func (UnimplementedLiquentAuctionRPCServer) AuctionEndpoint(context.Context, *AuctionEndpointRequest) (*AuctionEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuctionEndpoint not implemented")
}
func (UnimplementedLiquentAuctionRPCServer) Auctions(context.Context, *AuctionsRequest) (*AuctionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auctions not implemented")
}
func (UnimplementedLiquentAuctionRPCServer) StreamBids(*StreamBidsRequest, LiquentAuctionRPC_StreamBidsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamBids not implemented")
}
func (UnimplementedLiquentAuctionRPCServer) LqtBurntEndpoint(context.Context, *LqtBurntEndpointRequest) (*LqtBurntEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LqtBurntEndpoint not implemented")
}
func (UnimplementedLiquentAuctionRPCServer) mustEmbedUnimplementedLiquentAuctionRPCServer() {}

// UnsafeLiquentAuctionRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiquentAuctionRPCServer will
// result in compilation errors.
type UnsafeLiquentAuctionRPCServer interface {
	mustEmbedUnimplementedLiquentAuctionRPCServer()
}

func RegisterLiquentAuctionRPCServer(s grpc.ServiceRegistrar, srv LiquentAuctionRPCServer) {
	s.RegisterService(&LiquentAuctionRPC_ServiceDesc, srv)
}

func _LiquentAuctionRPC_AuctionEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentAuctionRPCServer).AuctionEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_auction_rpc.LiquentAuctionRPC/AuctionEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentAuctionRPCServer).AuctionEndpoint(ctx, req.(*AuctionEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentAuctionRPC_Auctions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentAuctionRPCServer).Auctions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_auction_rpc.LiquentAuctionRPC/Auctions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentAuctionRPCServer).Auctions(ctx, req.(*AuctionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentAuctionRPC_StreamBids_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBidsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentAuctionRPCServer).StreamBids(m, &liquentAuctionRPCStreamBidsServer{stream})
}

type LiquentAuctionRPC_StreamBidsServer interface {
	Send(*StreamBidsResponse) error
	grpc.ServerStream
}

type liquentAuctionRPCStreamBidsServer struct {
	grpc.ServerStream
}

func (x *liquentAuctionRPCStreamBidsServer) Send(m *StreamBidsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentAuctionRPC_LqtBurntEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LqtBurntEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentAuctionRPCServer).LqtBurntEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_auction_rpc.LiquentAuctionRPC/LqtBurntEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentAuctionRPCServer).LqtBurntEndpoint(ctx, req.(*LqtBurntEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LiquentAuctionRPC_ServiceDesc is the grpc.ServiceDesc for LiquentAuctionRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiquentAuctionRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "liquent_auction_rpc.LiquentAuctionRPC",
	HandlerType: (*LiquentAuctionRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuctionEndpoint",
			Handler:    _LiquentAuctionRPC_AuctionEndpoint_Handler,
		},
		{
			MethodName: "Auctions",
			Handler:    _LiquentAuctionRPC_Auctions_Handler,
		},
		{
			MethodName: "LqtBurntEndpoint",
			Handler:    _LiquentAuctionRPC_LqtBurntEndpoint_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBids",
			Handler:       _LiquentAuctionRPC_StreamBids_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "goadesign_goagen_liquent_auction_rpc.proto",
}
