// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: goadesign_goagen_liquent_meta_rpc.proto

package liquent_meta_rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LiquentMetaRPCClient is the client API for LiquentMetaRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiquentMetaRPCClient interface {
	// Endpoint for checking server health.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Returns liquent-exchange version.
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	// Gets connection info
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	// Stream keepalive, if server exits, a shutdown event will be sent over this
	// channel.
	StreamKeepalive(ctx context.Context, in *StreamKeepaliveRequest, opts ...grpc.CallOption) (LiquentMetaRPC_StreamKeepaliveClient, error)
	// Get tokens metadata. Can be filtered by denom
	TokenMetadata(ctx context.Context, in *TokenMetadataRequest, opts ...grpc.CallOption) (*TokenMetadataResponse, error)
}

type liquentMetaRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewLiquentMetaRPCClient(cc grpc.ClientConnInterface) LiquentMetaRPCClient {
	return &liquentMetaRPCClient{cc}
}

func (c *liquentMetaRPCClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/liquent_meta_rpc.LiquentMetaRPC/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentMetaRPCClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/liquent_meta_rpc.LiquentMetaRPC/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentMetaRPCClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/liquent_meta_rpc.LiquentMetaRPC/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentMetaRPCClient) StreamKeepalive(ctx context.Context, in *StreamKeepaliveRequest, opts ...grpc.CallOption) (LiquentMetaRPC_StreamKeepaliveClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentMetaRPC_ServiceDesc.Streams[0], "/liquent_meta_rpc.LiquentMetaRPC/StreamKeepalive", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentMetaRPCStreamKeepaliveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentMetaRPC_StreamKeepaliveClient interface {
	Recv() (*StreamKeepaliveResponse, error)
	grpc.ClientStream
}

type liquentMetaRPCStreamKeepaliveClient struct {
	grpc.ClientStream
}

func (x *liquentMetaRPCStreamKeepaliveClient) Recv() (*StreamKeepaliveResponse, error) {
	m := new(StreamKeepaliveResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentMetaRPCClient) TokenMetadata(ctx context.Context, in *TokenMetadataRequest, opts ...grpc.CallOption) (*TokenMetadataResponse, error) {
	out := new(TokenMetadataResponse)
	err := c.cc.Invoke(ctx, "/liquent_meta_rpc.LiquentMetaRPC/TokenMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiquentMetaRPCServer is the server API for LiquentMetaRPC service.
// All implementations must embed UnimplementedLiquentMetaRPCServer
// for forward compatibility
type LiquentMetaRPCServer interface {
	// Endpoint for checking server health.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Returns liquent-exchange version.
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	// Gets connection info
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	// Stream keepalive, if server exits, a shutdown event will be sent over this
	// channel.
	StreamKeepalive(*StreamKeepaliveRequest, LiquentMetaRPC_StreamKeepaliveServer) error
	// Get tokens metadata. Can be filtered by denom
	TokenMetadata(context.Context, *TokenMetadataRequest) (*TokenMetadataResponse, error)
	mustEmbedUnimplementedLiquentMetaRPCServer()
}

// UnimplementedLiquentMetaRPCServer must be embedded to have forward compatible implementations.
type UnimplementedLiquentMetaRPCServer struct {
}

func (UnimplementedLiquentMetaRPCServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedLiquentMetaRPCServer) Version(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedLiquentMetaRPCServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedLiquentMetaRPCServer) StreamKeepalive(*StreamKeepaliveRequest, LiquentMetaRPC_StreamKeepaliveServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamKeepalive not implemented")
}
func (UnimplementedLiquentMetaRPCServer) TokenMetadata(context.Context, *TokenMetadataRequest) (*TokenMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenMetadata not implemented")
}
func (UnimplementedLiquentMetaRPCServer) mustEmbedUnimplementedLiquentMetaRPCServer() {}

// UnsafeLiquentMetaRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiquentMetaRPCServer will
// result in compilation errors.
type UnsafeLiquentMetaRPCServer interface {
	mustEmbedUnimplementedLiquentMetaRPCServer()
}

func RegisterLiquentMetaRPCServer(s grpc.ServiceRegistrar, srv LiquentMetaRPCServer) {
	s.RegisterService(&LiquentMetaRPC_ServiceDesc, srv)
}

func _LiquentMetaRPC_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentMetaRPCServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_meta_rpc.LiquentMetaRPC/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentMetaRPCServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentMetaRPC_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentMetaRPCServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_meta_rpc.LiquentMetaRPC/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentMetaRPCServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentMetaRPC_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentMetaRPCServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_meta_rpc.LiquentMetaRPC/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentMetaRPCServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentMetaRPC_StreamKeepalive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamKeepaliveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentMetaRPCServer).StreamKeepalive(m, &liquentMetaRPCStreamKeepaliveServer{stream})
}

type LiquentMetaRPC_StreamKeepaliveServer interface {
	Send(*StreamKeepaliveResponse) error
	grpc.ServerStream
}

type liquentMetaRPCStreamKeepaliveServer struct {
	grpc.ServerStream
}

func (x *liquentMetaRPCStreamKeepaliveServer) Send(m *StreamKeepaliveResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentMetaRPC_TokenMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentMetaRPCServer).TokenMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_meta_rpc.LiquentMetaRPC/TokenMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentMetaRPCServer).TokenMetadata(ctx, req.(*TokenMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LiquentMetaRPC_ServiceDesc is the grpc.ServiceDesc for LiquentMetaRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiquentMetaRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "liquent_meta_rpc.LiquentMetaRPC",
	HandlerType: (*LiquentMetaRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _LiquentMetaRPC_Ping_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _LiquentMetaRPC_Version_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _LiquentMetaRPC_Info_Handler,
		},
		{
			MethodName: "TokenMetadata",
			Handler:    _LiquentMetaRPC_TokenMetadata_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamKeepalive",
			Handler:       _LiquentMetaRPC_StreamKeepalive_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "goadesign_goagen_liquent_meta_rpc.proto",
}
