// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: goadesign_goagen_liquent_explorer_rpc.proto

package liquent_explorer_rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LiquentExplorerRPCClient is the client API for LiquentExplorerRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiquentExplorerRPCClient interface {
	// GetAccountTxs returns tranctions involving in an account based upon params.
	GetAccountTxs(ctx context.Context, in *GetAccountTxsRequest, opts ...grpc.CallOption) (*GetAccountTxsResponse, error)
	// GetAccountTxs returns tranctions involving in an account based upon params.
	GetAccountTxsV2(ctx context.Context, in *GetAccountTxsV2Request, opts ...grpc.CallOption) (*GetAccountTxsV2Response, error)
	// GetContractTxs returns contract-related transactions
	GetContractTxs(ctx context.Context, in *GetContractTxsRequest, opts ...grpc.CallOption) (*GetContractTxsResponse, error)
	// GetContractTxs returns contract-related transactions
	GetContractTxsV2(ctx context.Context, in *GetContractTxsV2Request, opts ...grpc.CallOption) (*GetContractTxsV2Response, error)
	// GetBlocks returns blocks based upon the request params
	GetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (*GetBlocksResponse, error)
	// GetBlocks returns blocks based upon the request params
	GetBlocksV2(ctx context.Context, in *GetBlocksV2Request, opts ...grpc.CallOption) (*GetBlocksV2Response, error)
	// GetBlock returns block based upon the height or hash
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error)
	// GetValidators returns validators on the active chain
	GetValidators(ctx context.Context, in *GetValidatorsRequest, opts ...grpc.CallOption) (*GetValidatorsResponse, error)
	// GetValidator returns validator information on the active chain
	GetValidator(ctx context.Context, in *GetValidatorRequest, opts ...grpc.CallOption) (*GetValidatorResponse, error)
	// GetValidatorUptime returns validator uptime information on the active chain
	GetValidatorUptime(ctx context.Context, in *GetValidatorUptimeRequest, opts ...grpc.CallOption) (*GetValidatorUptimeResponse, error)
	// GetTxs returns transactions based upon the request params
	GetTxs(ctx context.Context, in *GetTxsRequest, opts ...grpc.CallOption) (*GetTxsResponse, error)
	// GetTxs returns transactions based upon the request params
	GetTxsV2(ctx context.Context, in *GetTxsV2Request, opts ...grpc.CallOption) (*GetTxsV2Response, error)
	// GetTxByTxHash returns certain transaction information by its tx hash.
	GetTxByTxHash(ctx context.Context, in *GetTxByTxHashRequest, opts ...grpc.CallOption) (*GetTxByTxHashResponse, error)
	// GetPeggyDepositTxs returns the peggy deposit transactions based upon the
	// request params
	GetPeggyDepositTxs(ctx context.Context, in *GetPeggyDepositTxsRequest, opts ...grpc.CallOption) (*GetPeggyDepositTxsResponse, error)
	// GetPeggyWithdrawalTxs returns the peggy withdrawal transactions based upon
	// the request params
	GetPeggyWithdrawalTxs(ctx context.Context, in *GetPeggyWithdrawalTxsRequest, opts ...grpc.CallOption) (*GetPeggyWithdrawalTxsResponse, error)
	// GetIBCTransferTxs returns the ibc transfer transactions based upon the
	// request params
	GetIBCTransferTxs(ctx context.Context, in *GetIBCTransferTxsRequest, opts ...grpc.CallOption) (*GetIBCTransferTxsResponse, error)
	// GetWasmCodes lists all stored code
	GetWasmCodes(ctx context.Context, in *GetWasmCodesRequest, opts ...grpc.CallOption) (*GetWasmCodesResponse, error)
	// GetWasmCodeById list cosmwasm code infor by ID
	GetWasmCodeByID(ctx context.Context, in *GetWasmCodeByIDRequest, opts ...grpc.CallOption) (*GetWasmCodeByIDResponse, error)
	// GetWasmContracts lists all contracts
	GetWasmContracts(ctx context.Context, in *GetWasmContractsRequest, opts ...grpc.CallOption) (*GetWasmContractsResponse, error)
	// GetWasmContractByAddress list cosmwasm contract info by its address
	GetWasmContractByAddress(ctx context.Context, in *GetWasmContractByAddressRequest, opts ...grpc.CallOption) (*GetWasmContractByAddressResponse, error)
	// GetCw20Balance lists all cw20 balances of an liquent account
	GetCw20Balance(ctx context.Context, in *GetCw20BalanceRequest, opts ...grpc.CallOption) (*GetCw20BalanceResponse, error)
	// Request relayers infos by marketIDs. If no ids are provided, all market with
	// associated relayers are returned
	Relayers(ctx context.Context, in *RelayersRequest, opts ...grpc.CallOption) (*RelayersResponse, error)
	// GetBankTransfers returns bank transfers.
	GetBankTransfers(ctx context.Context, in *GetBankTransfersRequest, opts ...grpc.CallOption) (*GetBankTransfersResponse, error)
	// StreamTxs returns transactions based upon the request params
	StreamTxs(ctx context.Context, in *StreamTxsRequest, opts ...grpc.CallOption) (LiquentExplorerRPC_StreamTxsClient, error)
	// StreamBlocks returns the latest blocks
	StreamBlocks(ctx context.Context, in *StreamBlocksRequest, opts ...grpc.CallOption) (LiquentExplorerRPC_StreamBlocksClient, error)
	// GetStats returns global exchange statistics in the last 24hs
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
}

type liquentExplorerRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewLiquentExplorerRPCClient(cc grpc.ClientConnInterface) LiquentExplorerRPCClient {
	return &liquentExplorerRPCClient{cc}
}

func (c *liquentExplorerRPCClient) GetAccountTxs(ctx context.Context, in *GetAccountTxsRequest, opts ...grpc.CallOption) (*GetAccountTxsResponse, error) {
	out := new(GetAccountTxsResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetAccountTxs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetAccountTxsV2(ctx context.Context, in *GetAccountTxsV2Request, opts ...grpc.CallOption) (*GetAccountTxsV2Response, error) {
	out := new(GetAccountTxsV2Response)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetAccountTxsV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetContractTxs(ctx context.Context, in *GetContractTxsRequest, opts ...grpc.CallOption) (*GetContractTxsResponse, error) {
	out := new(GetContractTxsResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetContractTxs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetContractTxsV2(ctx context.Context, in *GetContractTxsV2Request, opts ...grpc.CallOption) (*GetContractTxsV2Response, error) {
	out := new(GetContractTxsV2Response)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetContractTxsV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (*GetBlocksResponse, error) {
	out := new(GetBlocksResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetBlocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetBlocksV2(ctx context.Context, in *GetBlocksV2Request, opts ...grpc.CallOption) (*GetBlocksV2Response, error) {
	out := new(GetBlocksV2Response)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetBlocksV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error) {
	out := new(GetBlockResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetValidators(ctx context.Context, in *GetValidatorsRequest, opts ...grpc.CallOption) (*GetValidatorsResponse, error) {
	out := new(GetValidatorsResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetValidators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetValidator(ctx context.Context, in *GetValidatorRequest, opts ...grpc.CallOption) (*GetValidatorResponse, error) {
	out := new(GetValidatorResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetValidator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetValidatorUptime(ctx context.Context, in *GetValidatorUptimeRequest, opts ...grpc.CallOption) (*GetValidatorUptimeResponse, error) {
	out := new(GetValidatorUptimeResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetValidatorUptime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetTxs(ctx context.Context, in *GetTxsRequest, opts ...grpc.CallOption) (*GetTxsResponse, error) {
	out := new(GetTxsResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetTxs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetTxsV2(ctx context.Context, in *GetTxsV2Request, opts ...grpc.CallOption) (*GetTxsV2Response, error) {
	out := new(GetTxsV2Response)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetTxsV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetTxByTxHash(ctx context.Context, in *GetTxByTxHashRequest, opts ...grpc.CallOption) (*GetTxByTxHashResponse, error) {
	out := new(GetTxByTxHashResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetTxByTxHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetPeggyDepositTxs(ctx context.Context, in *GetPeggyDepositTxsRequest, opts ...grpc.CallOption) (*GetPeggyDepositTxsResponse, error) {
	out := new(GetPeggyDepositTxsResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetPeggyDepositTxs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetPeggyWithdrawalTxs(ctx context.Context, in *GetPeggyWithdrawalTxsRequest, opts ...grpc.CallOption) (*GetPeggyWithdrawalTxsResponse, error) {
	out := new(GetPeggyWithdrawalTxsResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetPeggyWithdrawalTxs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetIBCTransferTxs(ctx context.Context, in *GetIBCTransferTxsRequest, opts ...grpc.CallOption) (*GetIBCTransferTxsResponse, error) {
	out := new(GetIBCTransferTxsResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetIBCTransferTxs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetWasmCodes(ctx context.Context, in *GetWasmCodesRequest, opts ...grpc.CallOption) (*GetWasmCodesResponse, error) {
	out := new(GetWasmCodesResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetWasmCodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetWasmCodeByID(ctx context.Context, in *GetWasmCodeByIDRequest, opts ...grpc.CallOption) (*GetWasmCodeByIDResponse, error) {
	out := new(GetWasmCodeByIDResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetWasmCodeByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetWasmContracts(ctx context.Context, in *GetWasmContractsRequest, opts ...grpc.CallOption) (*GetWasmContractsResponse, error) {
	out := new(GetWasmContractsResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetWasmContracts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetWasmContractByAddress(ctx context.Context, in *GetWasmContractByAddressRequest, opts ...grpc.CallOption) (*GetWasmContractByAddressResponse, error) {
	out := new(GetWasmContractByAddressResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetWasmContractByAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetCw20Balance(ctx context.Context, in *GetCw20BalanceRequest, opts ...grpc.CallOption) (*GetCw20BalanceResponse, error) {
	out := new(GetCw20BalanceResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetCw20Balance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) Relayers(ctx context.Context, in *RelayersRequest, opts ...grpc.CallOption) (*RelayersResponse, error) {
	out := new(RelayersResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/Relayers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) GetBankTransfers(ctx context.Context, in *GetBankTransfersRequest, opts ...grpc.CallOption) (*GetBankTransfersResponse, error) {
	out := new(GetBankTransfersResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetBankTransfers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentExplorerRPCClient) StreamTxs(ctx context.Context, in *StreamTxsRequest, opts ...grpc.CallOption) (LiquentExplorerRPC_StreamTxsClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentExplorerRPC_ServiceDesc.Streams[0], "/liquent_explorer_rpc.LiquentExplorerRPC/StreamTxs", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentExplorerRPCStreamTxsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentExplorerRPC_StreamTxsClient interface {
	Recv() (*StreamTxsResponse, error)
	grpc.ClientStream
}

type liquentExplorerRPCStreamTxsClient struct {
	grpc.ClientStream
}

func (x *liquentExplorerRPCStreamTxsClient) Recv() (*StreamTxsResponse, error) {
	m := new(StreamTxsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentExplorerRPCClient) StreamBlocks(ctx context.Context, in *StreamBlocksRequest, opts ...grpc.CallOption) (LiquentExplorerRPC_StreamBlocksClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentExplorerRPC_ServiceDesc.Streams[1], "/liquent_explorer_rpc.LiquentExplorerRPC/StreamBlocks", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentExplorerRPCStreamBlocksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentExplorerRPC_StreamBlocksClient interface {
	Recv() (*StreamBlocksResponse, error)
	grpc.ClientStream
}

type liquentExplorerRPCStreamBlocksClient struct {
	grpc.ClientStream
}

func (x *liquentExplorerRPCStreamBlocksClient) Recv() (*StreamBlocksResponse, error) {
	m := new(StreamBlocksResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentExplorerRPCClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, "/liquent_explorer_rpc.LiquentExplorerRPC/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiquentExplorerRPCServer is the server API for LiquentExplorerRPC service.
// All implementations must embed UnimplementedLiquentExplorerRPCServer
// for forward compatibility
type LiquentExplorerRPCServer interface {
	// GetAccountTxs returns tranctions involving in an account based upon params.
	GetAccountTxs(context.Context, *GetAccountTxsRequest) (*GetAccountTxsResponse, error)
	// GetAccountTxs returns tranctions involving in an account based upon params.
	GetAccountTxsV2(context.Context, *GetAccountTxsV2Request) (*GetAccountTxsV2Response, error)
	// GetContractTxs returns contract-related transactions
	GetContractTxs(context.Context, *GetContractTxsRequest) (*GetContractTxsResponse, error)
	// GetContractTxs returns contract-related transactions
	GetContractTxsV2(context.Context, *GetContractTxsV2Request) (*GetContractTxsV2Response, error)
	// GetBlocks returns blocks based upon the request params
	GetBlocks(context.Context, *GetBlocksRequest) (*GetBlocksResponse, error)
	// GetBlocks returns blocks based upon the request params
	GetBlocksV2(context.Context, *GetBlocksV2Request) (*GetBlocksV2Response, error)
	// GetBlock returns block based upon the height or hash
	GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error)
	// GetValidators returns validators on the active chain
	GetValidators(context.Context, *GetValidatorsRequest) (*GetValidatorsResponse, error)
	// GetValidator returns validator information on the active chain
	GetValidator(context.Context, *GetValidatorRequest) (*GetValidatorResponse, error)
	// GetValidatorUptime returns validator uptime information on the active chain
	GetValidatorUptime(context.Context, *GetValidatorUptimeRequest) (*GetValidatorUptimeResponse, error)
	// GetTxs returns transactions based upon the request params
	GetTxs(context.Context, *GetTxsRequest) (*GetTxsResponse, error)
	// GetTxs returns transactions based upon the request params
	GetTxsV2(context.Context, *GetTxsV2Request) (*GetTxsV2Response, error)
	// GetTxByTxHash returns certain transaction information by its tx hash.
	GetTxByTxHash(context.Context, *GetTxByTxHashRequest) (*GetTxByTxHashResponse, error)
	// GetPeggyDepositTxs returns the peggy deposit transactions based upon the
	// request params
	GetPeggyDepositTxs(context.Context, *GetPeggyDepositTxsRequest) (*GetPeggyDepositTxsResponse, error)
	// GetPeggyWithdrawalTxs returns the peggy withdrawal transactions based upon
	// the request params
	GetPeggyWithdrawalTxs(context.Context, *GetPeggyWithdrawalTxsRequest) (*GetPeggyWithdrawalTxsResponse, error)
	// GetIBCTransferTxs returns the ibc transfer transactions based upon the
	// request params
	GetIBCTransferTxs(context.Context, *GetIBCTransferTxsRequest) (*GetIBCTransferTxsResponse, error)
	// GetWasmCodes lists all stored code
	GetWasmCodes(context.Context, *GetWasmCodesRequest) (*GetWasmCodesResponse, error)
	// GetWasmCodeById list cosmwasm code infor by ID
	GetWasmCodeByID(context.Context, *GetWasmCodeByIDRequest) (*GetWasmCodeByIDResponse, error)
	// GetWasmContracts lists all contracts
	GetWasmContracts(context.Context, *GetWasmContractsRequest) (*GetWasmContractsResponse, error)
	// GetWasmContractByAddress list cosmwasm contract info by its address
	GetWasmContractByAddress(context.Context, *GetWasmContractByAddressRequest) (*GetWasmContractByAddressResponse, error)
	// GetCw20Balance lists all cw20 balances of an liquent account
	GetCw20Balance(context.Context, *GetCw20BalanceRequest) (*GetCw20BalanceResponse, error)
	// Request relayers infos by marketIDs. If no ids are provided, all market with
	// associated relayers are returned
	Relayers(context.Context, *RelayersRequest) (*RelayersResponse, error)
	// GetBankTransfers returns bank transfers.
	GetBankTransfers(context.Context, *GetBankTransfersRequest) (*GetBankTransfersResponse, error)
	// StreamTxs returns transactions based upon the request params
	StreamTxs(*StreamTxsRequest, LiquentExplorerRPC_StreamTxsServer) error
	// StreamBlocks returns the latest blocks
	StreamBlocks(*StreamBlocksRequest, LiquentExplorerRPC_StreamBlocksServer) error
	// GetStats returns global exchange statistics in the last 24hs
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	mustEmbedUnimplementedLiquentExplorerRPCServer()
}

// UnimplementedLiquentExplorerRPCServer must be embedded to have forward compatible implementations.
type UnimplementedLiquentExplorerRPCServer struct {
}

func (UnimplementedLiquentExplorerRPCServer) GetAccountTxs(context.Context, *GetAccountTxsRequest) (*GetAccountTxsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountTxs not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetAccountTxsV2(context.Context, *GetAccountTxsV2Request) (*GetAccountTxsV2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountTxsV2 not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetContractTxs(context.Context, *GetContractTxsRequest) (*GetContractTxsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContractTxs not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetContractTxsV2(context.Context, *GetContractTxsV2Request) (*GetContractTxsV2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContractTxsV2 not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetBlocks(context.Context, *GetBlocksRequest) (*GetBlocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlocks not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetBlocksV2(context.Context, *GetBlocksV2Request) (*GetBlocksV2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlocksV2 not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlock not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetValidators(context.Context, *GetValidatorsRequest) (*GetValidatorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidators not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetValidator(context.Context, *GetValidatorRequest) (*GetValidatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidator not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetValidatorUptime(context.Context, *GetValidatorUptimeRequest) (*GetValidatorUptimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidatorUptime not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetTxs(context.Context, *GetTxsRequest) (*GetTxsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTxs not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetTxsV2(context.Context, *GetTxsV2Request) (*GetTxsV2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTxsV2 not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetTxByTxHash(context.Context, *GetTxByTxHashRequest) (*GetTxByTxHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTxByTxHash not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetPeggyDepositTxs(context.Context, *GetPeggyDepositTxsRequest) (*GetPeggyDepositTxsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeggyDepositTxs not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetPeggyWithdrawalTxs(context.Context, *GetPeggyWithdrawalTxsRequest) (*GetPeggyWithdrawalTxsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeggyWithdrawalTxs not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetIBCTransferTxs(context.Context, *GetIBCTransferTxsRequest) (*GetIBCTransferTxsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIBCTransferTxs not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetWasmCodes(context.Context, *GetWasmCodesRequest) (*GetWasmCodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWasmCodes not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetWasmCodeByID(context.Context, *GetWasmCodeByIDRequest) (*GetWasmCodeByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWasmCodeByID not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetWasmContracts(context.Context, *GetWasmContractsRequest) (*GetWasmContractsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWasmContracts not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetWasmContractByAddress(context.Context, *GetWasmContractByAddressRequest) (*GetWasmContractByAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWasmContractByAddress not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetCw20Balance(context.Context, *GetCw20BalanceRequest) (*GetCw20BalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCw20Balance not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) Relayers(context.Context, *RelayersRequest) (*RelayersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Relayers not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetBankTransfers(context.Context, *GetBankTransfersRequest) (*GetBankTransfersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBankTransfers not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) StreamTxs(*StreamTxsRequest, LiquentExplorerRPC_StreamTxsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamTxs not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) StreamBlocks(*StreamBlocksRequest, LiquentExplorerRPC_StreamBlocksServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamBlocks not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedLiquentExplorerRPCServer) mustEmbedUnimplementedLiquentExplorerRPCServer() {}

// UnsafeLiquentExplorerRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiquentExplorerRPCServer will
// result in compilation errors.
type UnsafeLiquentExplorerRPCServer interface {
	mustEmbedUnimplementedLiquentExplorerRPCServer()
}

func RegisterLiquentExplorerRPCServer(s grpc.ServiceRegistrar, srv LiquentExplorerRPCServer) {
	s.RegisterService(&LiquentExplorerRPC_ServiceDesc, srv)
}

func _LiquentExplorerRPC_GetAccountTxs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountTxsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetAccountTxs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetAccountTxs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetAccountTxs(ctx, req.(*GetAccountTxsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetAccountTxsV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountTxsV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetAccountTxsV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetAccountTxsV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetAccountTxsV2(ctx, req.(*GetAccountTxsV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetContractTxs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContractTxsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetContractTxs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetContractTxs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetContractTxs(ctx, req.(*GetContractTxsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetContractTxsV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContractTxsV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetContractTxsV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetContractTxsV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetContractTxsV2(ctx, req.(*GetContractTxsV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetBlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetBlocks(ctx, req.(*GetBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetBlocksV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlocksV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetBlocksV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetBlocksV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetBlocksV2(ctx, req.(*GetBlocksV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetValidators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetValidators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetValidators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetValidators(ctx, req.(*GetValidatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetValidator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetValidator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetValidator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetValidator(ctx, req.(*GetValidatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetValidatorUptime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidatorUptimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetValidatorUptime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetValidatorUptime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetValidatorUptime(ctx, req.(*GetValidatorUptimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetTxs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetTxs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetTxs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetTxs(ctx, req.(*GetTxsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetTxsV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxsV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetTxsV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetTxsV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetTxsV2(ctx, req.(*GetTxsV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetTxByTxHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxByTxHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetTxByTxHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetTxByTxHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetTxByTxHash(ctx, req.(*GetTxByTxHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetPeggyDepositTxs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeggyDepositTxsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetPeggyDepositTxs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetPeggyDepositTxs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetPeggyDepositTxs(ctx, req.(*GetPeggyDepositTxsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetPeggyWithdrawalTxs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeggyWithdrawalTxsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetPeggyWithdrawalTxs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetPeggyWithdrawalTxs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetPeggyWithdrawalTxs(ctx, req.(*GetPeggyWithdrawalTxsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetIBCTransferTxs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIBCTransferTxsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetIBCTransferTxs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetIBCTransferTxs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetIBCTransferTxs(ctx, req.(*GetIBCTransferTxsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetWasmCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWasmCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetWasmCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetWasmCodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetWasmCodes(ctx, req.(*GetWasmCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetWasmCodeByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWasmCodeByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetWasmCodeByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetWasmCodeByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetWasmCodeByID(ctx, req.(*GetWasmCodeByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetWasmContracts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWasmContractsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetWasmContracts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetWasmContracts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetWasmContracts(ctx, req.(*GetWasmContractsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetWasmContractByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWasmContractByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetWasmContractByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetWasmContractByAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetWasmContractByAddress(ctx, req.(*GetWasmContractByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetCw20Balance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCw20BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetCw20Balance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetCw20Balance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetCw20Balance(ctx, req.(*GetCw20BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_Relayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).Relayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/Relayers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).Relayers(ctx, req.(*RelayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_GetBankTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBankTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetBankTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetBankTransfers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetBankTransfers(ctx, req.(*GetBankTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentExplorerRPC_StreamTxs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTxsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentExplorerRPCServer).StreamTxs(m, &liquentExplorerRPCStreamTxsServer{stream})
}

type LiquentExplorerRPC_StreamTxsServer interface {
	Send(*StreamTxsResponse) error
	grpc.ServerStream
}

type liquentExplorerRPCStreamTxsServer struct {
	grpc.ServerStream
}

func (x *liquentExplorerRPCStreamTxsServer) Send(m *StreamTxsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentExplorerRPC_StreamBlocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBlocksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentExplorerRPCServer).StreamBlocks(m, &liquentExplorerRPCStreamBlocksServer{stream})
}

type LiquentExplorerRPC_StreamBlocksServer interface {
	Send(*StreamBlocksResponse) error
	grpc.ServerStream
}

type liquentExplorerRPCStreamBlocksServer struct {
	grpc.ServerStream
}

func (x *liquentExplorerRPCStreamBlocksServer) Send(m *StreamBlocksResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentExplorerRPC_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentExplorerRPCServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_explorer_rpc.LiquentExplorerRPC/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentExplorerRPCServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LiquentExplorerRPC_ServiceDesc is the grpc.ServiceDesc for LiquentExplorerRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiquentExplorerRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "liquent_explorer_rpc.LiquentExplorerRPC",
	HandlerType: (*LiquentExplorerRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccountTxs",
			Handler:    _LiquentExplorerRPC_GetAccountTxs_Handler,
		},
		{
			MethodName: "GetAccountTxsV2",
			Handler:    _LiquentExplorerRPC_GetAccountTxsV2_Handler,
		},
		{
			MethodName: "GetContractTxs",
			Handler:    _LiquentExplorerRPC_GetContractTxs_Handler,
		},
		{
			MethodName: "GetContractTxsV2",
			Handler:    _LiquentExplorerRPC_GetContractTxsV2_Handler,
		},
		{
			MethodName: "GetBlocks",
			Handler:    _LiquentExplorerRPC_GetBlocks_Handler,
		},
		{
			MethodName: "GetBlocksV2",
			Handler:    _LiquentExplorerRPC_GetBlocksV2_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _LiquentExplorerRPC_GetBlock_Handler,
		},
		{
			MethodName: "GetValidators",
			Handler:    _LiquentExplorerRPC_GetValidators_Handler,
		},
		{
			MethodName: "GetValidator",
			Handler:    _LiquentExplorerRPC_GetValidator_Handler,
		},
		{
			MethodName: "GetValidatorUptime",
			Handler:    _LiquentExplorerRPC_GetValidatorUptime_Handler,
		},
		{
			MethodName: "GetTxs",
			Handler:    _LiquentExplorerRPC_GetTxs_Handler,
		},
		{
			MethodName: "GetTxsV2",
			Handler:    _LiquentExplorerRPC_GetTxsV2_Handler,
		},
		{
			MethodName: "GetTxByTxHash",
			Handler:    _LiquentExplorerRPC_GetTxByTxHash_Handler,
		},
		{
			MethodName: "GetPeggyDepositTxs",
			Handler:    _LiquentExplorerRPC_GetPeggyDepositTxs_Handler,
		},
		{
			MethodName: "GetPeggyWithdrawalTxs",
			Handler:    _LiquentExplorerRPC_GetPeggyWithdrawalTxs_Handler,
		},
		{
			MethodName: "GetIBCTransferTxs",
			Handler:    _LiquentExplorerRPC_GetIBCTransferTxs_Handler,
		},
		{
			MethodName: "GetWasmCodes",
			Handler:    _LiquentExplorerRPC_GetWasmCodes_Handler,
		},
		{
			MethodName: "GetWasmCodeByID",
			Handler:    _LiquentExplorerRPC_GetWasmCodeByID_Handler,
		},
		{
			MethodName: "GetWasmContracts",
			Handler:    _LiquentExplorerRPC_GetWasmContracts_Handler,
		},
		{
			MethodName: "GetWasmContractByAddress",
			Handler:    _LiquentExplorerRPC_GetWasmContractByAddress_Handler,
		},
		{
			MethodName: "GetCw20Balance",
			Handler:    _LiquentExplorerRPC_GetCw20Balance_Handler,
		},
		{
			MethodName: "Relayers",
			Handler:    _LiquentExplorerRPC_Relayers_Handler,
		},
		{
			MethodName: "GetBankTransfers",
			Handler:    _LiquentExplorerRPC_GetBankTransfers_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _LiquentExplorerRPC_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTxs",
			Handler:       _LiquentExplorerRPC_StreamTxs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamBlocks",
			Handler:       _LiquentExplorerRPC_StreamBlocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "goadesign_goagen_liquent_explorer_rpc.proto",
}
