// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: goadesign_goagen_liquent_oracle_rpc.proto

package liquent_oracle_rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LiquentOracleRPCClient is the client API for LiquentOracleRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiquentOracleRPCClient interface {
	// List all oracles
	OracleList(ctx context.Context, in *OracleListRequest, opts ...grpc.CallOption) (*OracleListResponse, error)
	// Gets the price of the oracle
	Price(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*PriceResponse, error)
	// Gets prices of the oracle
	PriceV2(ctx context.Context, in *PriceV2Request, opts ...grpc.CallOption) (*PriceV2Response, error)
	// StreamPrices streams new price changes for a specified oracle. If no oracles
	// are provided, all price changes are streamed.
	StreamPrices(ctx context.Context, in *StreamPricesRequest, opts ...grpc.CallOption) (LiquentOracleRPC_StreamPricesClient, error)
	// StreamPrices streams new price changes markets
	StreamPricesByMarkets(ctx context.Context, in *StreamPricesByMarketsRequest, opts ...grpc.CallOption) (LiquentOracleRPC_StreamPricesByMarketsClient, error)
}

type liquentOracleRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewLiquentOracleRPCClient(cc grpc.ClientConnInterface) LiquentOracleRPCClient {
	return &liquentOracleRPCClient{cc}
}

func (c *liquentOracleRPCClient) OracleList(ctx context.Context, in *OracleListRequest, opts ...grpc.CallOption) (*OracleListResponse, error) {
	out := new(OracleListResponse)
	err := c.cc.Invoke(ctx, "/liquent_oracle_rpc.LiquentOracleRPC/OracleList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentOracleRPCClient) Price(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*PriceResponse, error) {
	out := new(PriceResponse)
	err := c.cc.Invoke(ctx, "/liquent_oracle_rpc.LiquentOracleRPC/Price", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentOracleRPCClient) PriceV2(ctx context.Context, in *PriceV2Request, opts ...grpc.CallOption) (*PriceV2Response, error) {
	out := new(PriceV2Response)
	err := c.cc.Invoke(ctx, "/liquent_oracle_rpc.LiquentOracleRPC/PriceV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liquentOracleRPCClient) StreamPrices(ctx context.Context, in *StreamPricesRequest, opts ...grpc.CallOption) (LiquentOracleRPC_StreamPricesClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentOracleRPC_ServiceDesc.Streams[0], "/liquent_oracle_rpc.LiquentOracleRPC/StreamPrices", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentOracleRPCStreamPricesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentOracleRPC_StreamPricesClient interface {
	Recv() (*StreamPricesResponse, error)
	grpc.ClientStream
}

type liquentOracleRPCStreamPricesClient struct {
	grpc.ClientStream
}

func (x *liquentOracleRPCStreamPricesClient) Recv() (*StreamPricesResponse, error) {
	m := new(StreamPricesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *liquentOracleRPCClient) StreamPricesByMarkets(ctx context.Context, in *StreamPricesByMarketsRequest, opts ...grpc.CallOption) (LiquentOracleRPC_StreamPricesByMarketsClient, error) {
	stream, err := c.cc.NewStream(ctx, &LiquentOracleRPC_ServiceDesc.Streams[1], "/liquent_oracle_rpc.LiquentOracleRPC/StreamPricesByMarkets", opts...)
	if err != nil {
		return nil, err
	}
	x := &liquentOracleRPCStreamPricesByMarketsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LiquentOracleRPC_StreamPricesByMarketsClient interface {
	Recv() (*StreamPricesByMarketsResponse, error)
	grpc.ClientStream
}

type liquentOracleRPCStreamPricesByMarketsClient struct {
	grpc.ClientStream
}

func (x *liquentOracleRPCStreamPricesByMarketsClient) Recv() (*StreamPricesByMarketsResponse, error) {
	m := new(StreamPricesByMarketsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LiquentOracleRPCServer is the server API for LiquentOracleRPC service.
// All implementations must embed UnimplementedLiquentOracleRPCServer
// for forward compatibility
type LiquentOracleRPCServer interface {
	// List all oracles
	OracleList(context.Context, *OracleListRequest) (*OracleListResponse, error)
	// Gets the price of the oracle
	Price(context.Context, *PriceRequest) (*PriceResponse, error)
	// Gets prices of the oracle
	PriceV2(context.Context, *PriceV2Request) (*PriceV2Response, error)
	// StreamPrices streams new price changes for a specified oracle. If no oracles
	// are provided, all price changes are streamed.
	StreamPrices(*StreamPricesRequest, LiquentOracleRPC_StreamPricesServer) error
	// StreamPrices streams new price changes markets
	StreamPricesByMarkets(*StreamPricesByMarketsRequest, LiquentOracleRPC_StreamPricesByMarketsServer) error
	mustEmbedUnimplementedLiquentOracleRPCServer()
}

// UnimplementedLiquentOracleRPCServer must be embedded to have forward compatible implementations.
type UnimplementedLiquentOracleRPCServer struct {
}

func (UnimplementedLiquentOracleRPCServer) OracleList(context.Context, *OracleListRequest) (*OracleListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OracleList not implemented")
}
func (UnimplementedLiquentOracleRPCServer) Price(context.Context, *PriceRequest) (*PriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Price not implemented")
}
func (UnimplementedLiquentOracleRPCServer) PriceV2(context.Context, *PriceV2Request) (*PriceV2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PriceV2 not implemented")
}
func (UnimplementedLiquentOracleRPCServer) StreamPrices(*StreamPricesRequest, LiquentOracleRPC_StreamPricesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPrices not implemented")
}
func (UnimplementedLiquentOracleRPCServer) StreamPricesByMarkets(*StreamPricesByMarketsRequest, LiquentOracleRPC_StreamPricesByMarketsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPricesByMarkets not implemented")
}
func (UnimplementedLiquentOracleRPCServer) mustEmbedUnimplementedLiquentOracleRPCServer() {}

// UnsafeLiquentOracleRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiquentOracleRPCServer will
// result in compilation errors.
type UnsafeLiquentOracleRPCServer interface {
	mustEmbedUnimplementedLiquentOracleRPCServer()
}

func RegisterLiquentOracleRPCServer(s grpc.ServiceRegistrar, srv LiquentOracleRPCServer) {
	s.RegisterService(&LiquentOracleRPC_ServiceDesc, srv)
}

func _LiquentOracleRPC_OracleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OracleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentOracleRPCServer).OracleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_oracle_rpc.LiquentOracleRPC/OracleList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentOracleRPCServer).OracleList(ctx, req.(*OracleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentOracleRPC_Price_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentOracleRPCServer).Price(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_oracle_rpc.LiquentOracleRPC/Price",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentOracleRPCServer).Price(ctx, req.(*PriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentOracleRPC_PriceV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquentOracleRPCServer).PriceV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liquent_oracle_rpc.LiquentOracleRPC/PriceV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquentOracleRPCServer).PriceV2(ctx, req.(*PriceV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiquentOracleRPC_StreamPrices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPricesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentOracleRPCServer).StreamPrices(m, &liquentOracleRPCStreamPricesServer{stream})
}

type LiquentOracleRPC_StreamPricesServer interface {
	Send(*StreamPricesResponse) error
	grpc.ServerStream
}

type liquentOracleRPCStreamPricesServer struct {
	grpc.ServerStream
}

func (x *liquentOracleRPCStreamPricesServer) Send(m *StreamPricesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LiquentOracleRPC_StreamPricesByMarkets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPricesByMarketsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LiquentOracleRPCServer).StreamPricesByMarkets(m, &liquentOracleRPCStreamPricesByMarketsServer{stream})
}

type LiquentOracleRPC_StreamPricesByMarketsServer interface {
	Send(*StreamPricesByMarketsResponse) error
	grpc.ServerStream
}

type liquentOracleRPCStreamPricesByMarketsServer struct {
	grpc.ServerStream
}

func (x *liquentOracleRPCStreamPricesByMarketsServer) Send(m *StreamPricesByMarketsResponse) error {
	return x.ServerStream.SendMsg(m)
}

// LiquentOracleRPC_ServiceDesc is the grpc.ServiceDesc for LiquentOracleRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiquentOracleRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "liquent_oracle_rpc.LiquentOracleRPC",
	HandlerType: (*LiquentOracleRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OracleList",
			Handler:    _LiquentOracleRPC_OracleList_Handler,
		},
		{
			MethodName: "Price",
			Handler:    _LiquentOracleRPC_Price_Handler,
		},
		{
			MethodName: "PriceV2",
			Handler:    _LiquentOracleRPC_PriceV2_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPrices",
			Handler:       _LiquentOracleRPC_StreamPrices_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamPricesByMarkets",
			Handler:       _LiquentOracleRPC_StreamPricesByMarkets_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "goadesign_goagen_liquent_oracle_rpc.proto",
}
